In [1]:
print("!! Jai Ganesh !!")

!! Jai Ganesh !!


In [2]:
import numpy as np
import pandas as pd

# Exercise

In [817]:
hotels=pd.read_csv('hotel_booking_data.csv')

In [474]:
hotels.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  customer_type  \
0                        0                     0       2  ...      Transient   
1                        0                     0       2  ...      Transient   
2                        0                     1       1  ...      Transient   
3                        0                     1       1  ...      Transient   
4                        0                     2       2  ...      Transient   

    adr required_car_parking_spaces total_of_special_requests  \
0   0.0                           0                         0   
1   0.0                           0                         0   
2  75.0                           0                         0   
3  75.0                           0                         0   
4  98.0                           0                         1   

  reservation_status reservation_status_date            name  \
0          Check-Out              2015-07-01   Ernest Barnes   
1          Check-Out              2015-07-01    Andrea Baker   
2          Check-Out              2015-07-02  Rebecca Parker   
3          Check-Out              2015-07-02    Laura Murray   
4          Check-Out              2015-07-03     Linda Hines   

                         email  phone-number       credit_card  
0  Ernest.Barnes31@outlook.com  669-792-1661  ************4322  
1       Andrea_Baker94@aol.com  858-637-6955  ************9157  
2   Rebecca_Parker@comcast.net  652-885-2745  ************3734  
3            Laura_M@gmail.com  364-656-8427  ************5677  
4           LHines@verizon.com  713-226-5883  ************5498  

[5 rows x 36 columns]

**TASK_1: How many rows are there?**


In [492]:
hotels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

ANS_1: There are total *119390* rows

    
**TASK_2: Is there any missing data? If so, which column has the most missing data?**


In [494]:
hotels.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [496]:
hotels['company'].isnull().value_counts()

True     112593
False      6797
Name: company, dtype: int64

In [511]:
hotels['company'].isnull().value_counts()[1]

112593

In [510]:
(hotels['company'].isnull().value_counts()[1])/((hotels['company'].isnull().value_counts()[1])+(hotels['company'].isnull().value_counts()[0]))*100

94.30689337465449

ANS_2: The 'Company' column has the most missing data = there is about *112593* entries i.e(*94.30% data in the column*) which are missing


**TASK_3: Drop the "company" column from the dataset.**


In [512]:
hotels.drop('company',axis=1,inplace=True)


**TASK_4: What are the top 5 most common country codes in the dataset?**


In [516]:
pd.set_option('display.max_columns', None)

In [848]:
hotels['country'].value_counts()[:5]

PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
Name: country, dtype: int64

**ANS_4: Top 5 Most common country codes are, PRT, GBR, FRA, ESP, & DEU**


**TASK_5: What is the name of the person who paid the highest ADR (average daily rate)? How much was their ADR?**


In [539]:
hotels[hotels['adr']==hotels['adr'].max()][['name','adr']]

name     adr
48515  Daniel Walter  5400.0

**ANS_5: Daniel Walter was the person who paid the highest ADR which was 5400.00/-**


**TASK_6: The adr is the average daily rate for a person's stay at the hotel. What is the mean adr across all the hotel stays in the dataset?**


In [540]:
hotels['adr'].mean()

101.83112153446453

ANS_6: the mean adr across all the hotel stays in the dataset is *101.83*


**TASK_7: What is the average (mean) number of nights for a stay across the entire data set? Feel free to round this to 2 decimal points.**


In [543]:
hotels[['stays_in_week_nights','stays_in_weekend_nights']]

stays_in_week_nights  stays_in_weekend_nights
0                          0                        0
1                          0                        0
2                          1                        0
3                          1                        0
4                          2                        0
...                      ...                      ...
119385                     5                        2
119386                     5                        2
119387                     5                        2
119388                     5                        2
119389                     7                        2

[119390 rows x 2 columns]

In [548]:
np.round(hotels['stays_in_week_nights'].mean() + hotels['stays_in_weekend_nights'].mean(),decimals=2)

3.43

ANS_7: The average (mean) number of nights for a stay across the entire data set is *3.43*


**TASK_8: What is the average total cost for a stay in the dataset? Not *average daily cost*, but *total* stay cost. (You will need to calculate total cost your self by using ADR and week day and weeknight stays). Feel free to round this to 2 decimal points.**


In [557]:
np.round(((hotels['stays_in_week_nights']+hotels['stays_in_weekend_nights'])*hotels['adr']).mean(),decimals=2)

357.85

ANS_8: The average total cost for a stay in the dataset *357.85/-*


**TASK_9: What are the names and emails of people who made exactly 5 "Special Requests"?**


In [574]:
hotels[hotels['total_of_special_requests']==5][['name','email']]

name                          email
7860             Amanda Harper           Amanda.H66@yahoo.com
11125            Laura Sanders      Sanders_Laura@hotmail.com
14596              Tommy Ortiz            Tommy_O@hotmail.com
14921           Gilbert Miller         Miller.Gilbert@aol.com
14922           Timothy Torres         TTorres@protonmail.com
24630          Jennifer Weaver             Jennifer_W@aol.com
27288           Crystal Horton             Crystal.H@mail.com
27477           Brittney Burke       Burke_Brittney16@att.com
29906          Cynthia Cabrera    Cabrera.Cynthia@xfinity.com
29949              Sarah Floyd              Sarah_F@gmail.com
32267           Michelle Villa         Michelle.Villa@aol.com
39027           Nichole Hebert       Hebert.Nichole@gmail.com
39129         Lindsey Mckenzie       Lindsey.Mckenzie@att.com
39525           Ashley Edwards       Edwards.Ashley@yahoo.com
70114       Christopher Torres   Torres.Christopher@gmail.com
78819   Mrs. Tara Sullivan DVM           Mrs..DVM@xfinity.com
78820           Michaela Brown          MichaelaBrown@att.com
78822        Kurt Maldonado MD              KMD15@xfinity.com
97072         Jason Richardson               Jason.R@zoho.com
97099             Terri Hurley            THurley@xfinity.com
97261        Mrs. Caitlin Webb             Mrs._W@comcast.net
98410             Holly Arroyo          Arroyo_Holly@mail.com
98674          Denise Campbell             Denise_C@gmail.com
99887            Michael Smith            Michael.S42@aol.com
99888       Dr. Trevor Sellers                  Dr._S@aol.com
101569            Kayla Murphy         Kayla.Murphy@yahoo.com
102061         Taylor Martinez    Taylor.Martinez@hotmail.com
109511          Charles Wilson       Charles_Wilson@yahoo.com
109590           Tyler Allison         Tyler.A@protonmail.com
110082          Matthew Bailey         Matthew_Bailey@aol.com
110083       Charlotte Acevedo        Charlotte_A@verizon.com
111909         Darrell Brennan  Brennan_Darrell51@hotmail.com
111911          Melinda Jensen         MelindaJensen@zoho.com
113915            Terry Arnold          Arnold.Terry@zoho.com
114770             Mary Nguyen     Nguyen.Mary@protonmail.com
114909          Lindsay Cuevas      Lindsay.Cuevas40@mail.com
116455       Cynthia Hernandez   CynthiaHernandez@xfinity.com
116457          Angela Hawkins             Angela_H@gmail.com
118817              Sue Lawson            Sue.L52@comcast.net
119161         Alyssa Richards        Alyssa_Richards@aol.com


**TASK_10: What percentage of hotel stays were classified as "repeat guests"? (Do not base this off the name of the person, but instead of the is_repeated_guest column)**

In [582]:
(hotels['is_repeated_guest'].value_counts()[1]/hotels['is_repeated_guest'].count())*100

3.191222045397437

ANS_10: *3.19%* percentage of hotel stays were classified as "repeat guests"

**TASK_11: What are the top 5 most common last name in the dataset? Bonus: Can you figure this out in one line of pandas code? (For simplicity treat the a title such as MD as a last name, for example Caroline Conley MD can be said to have the last name MD)**

In [598]:
(hotels['name'].apply(lambda x:x.split(" ")[-1])).value_counts()[:5]

Smith       2503
Johnson     1990
Williams    1618
Jones       1434
Brown       1423
Name: name, dtype: int64

**TASK_12: What are the names of the people who had booked the most number children and babies for their stay? (Don't worry if they canceled, only consider number of people reported at the time of their reservation)**

In [619]:
hotels[(hotels['children']==hotels['children'].max()) | (hotels['babies']==hotels['babies'].max())]['name']

328        Jamie Ramirez
46619    Nicholas Parker
Name: name, dtype: object

**TASK_13: What are the top 3 most common area code in the phone numbers? (Area code is first 3 digits)**

In [629]:
hotels['phone-number'].apply(lambda num:num.split("-")[0]).value_counts()[:3]

799    168
185    167
541    166
Name: phone-number, dtype: int64

**TASK_14: How many arrivals took place between the 1st and the 15th of the month (inclusive of 1 and 15) ? Bonus: Can you do this in one line of pandas code?**

In [646]:
(hotels['arrival_date_day_of_month'] <=15).sum()

58152


**HARD BONUS TASK_15: Create a table for counts for each day of the week that people arrived. (E.g. 5000 arrivals were on a Monday, 3000 were on a Tuesday, etc..)**

In [819]:
hotels['year']=hotels['arrival_date_year'].astype('str')
hotels['month']=hotels['arrival_date_month'].astype('str')
hotels['day']=hotels['arrival_date_day_of_month'].astype('str')



In [820]:
hotels['totaldate']=hotels['year']+'-'+hotels['month']+'-'+hotels['day']

In [821]:
hotels['totaldate']=pd.to_datetime(hotels['totaldate'])

In [822]:
hotels['day']=hotels['totaldate'].apply(lambda x:x.day_name())

In [823]:
hotels['total_people']=hotels['adults']+hotels['children']+hotels['babies']

In [824]:
hotels[hotels['reservation_status']=='Canceled']['adults']

8         2
9         2
10        2
27        2
32        2
         ..
107997    1
108000    1
110280    0
111355    1
111924    1
Name: adults, Length: 43017, dtype: int64

In [845]:
hotels['day'].value_counts()

Friday       19631
Thursday     19254
Monday       18171
Saturday     18055
Wednesday    16139
Sunday       14141
Tuesday      13999
Name: day, dtype: int64

# Classnotes

## pd.Series

In [4]:
myindex=['USA','CANADA','LONDON']
dates=[1776,1867,1821]

In [5]:
myser=pd.Series(data=dates)

In [6]:
myser

0    1776
1    1867
2    1821
dtype: int64

In [7]:
type(myser)

pandas.core.series.Series

In [8]:
myser=pd.Series(data=dates,index=myindex)

In [9]:
myser

USA       1776
CANADA    1867
LONDON    1821
dtype: int64

In [10]:
myser[2]

1821

In [11]:
myser['LONDON']

1821

In [12]:
ages={'Sam':5,'Frank':10,'Spike':7}

In [13]:
pd.Series(ages)

Sam       5
Frank    10
Spike     7
dtype: int64

In [14]:
# Imaginary Sales Data for 1st and 2nd Quarters for Global Company
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}
q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}

In [15]:
sales_q1=pd.Series(q1)
sales_q2=pd.Series(q2)

In [16]:
sales_q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [17]:
sales_q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [18]:
sales_q1['India']

200

In [19]:
sales_q2['India']

210

In [20]:
sales_q1[2]

200

In [21]:
sales_q1.keys()

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [22]:
[1,2]*2

[1, 2, 1, 2]

In [23]:
np.array([1,2])*2

array([2, 4])

In [24]:
sales_q1*2

Japan    160
China    900
India    400
USA      500
dtype: int64

In [25]:
sales_q1+sales_q2

Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64

In [26]:
sales_q1.add(sales_q2,fill_value=0)

Brazil    100.0
China     950.0
India     410.0
Japan      80.0
USA       510.0
dtype: float64

## pd.DataFrame

In [27]:
np.random.seed(101)
mydata=np.random.randint(0,101,(4,3))

In [28]:
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [29]:
myindex=['CA','NY','AZ','TX']

In [30]:
mycolumns=['Jan','Feb','Mar']

In [31]:
df=pd.DataFrame(data=mydata)

In [32]:
df

0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [33]:
df=pd.DataFrame(data=mydata,index=myindex)

In [34]:
df

0   1   2
CA  95  11  81
NY  70  63  87
AZ  75   9  77
TX  40   4  63

In [35]:
df=pd.DataFrame(data=mydata,index=myindex,columns=mycolumns)
df

Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes


In [37]:
# WHERE IS MY PYTHON CODE LOCATED

In [38]:
pwd

'C:\\Users\\pkana\\Pierian Data Inc\\Python for Machine Learning & Data Science Masterclass\\03-Pandas'

In [39]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 1C0B-77D4

 Directory of C:\Users\pkana\Pierian Data Inc\Python for Machine Learning & Data Science Masterclass\03-Pandas

18-05-2022  12:02 PM    <DIR>          .
12-05-2022  11:52 AM    <DIR>          ..
13-05-2022  12:01 PM    <DIR>          .ipynb_checkpoints
13-07-2020  12:37 AM    <DIR>          __pycache__
13-05-2022  05:59 PM           565,402 00-Series.ipynb
08-09-2020  11:29 PM           208,957 01-DataFrames.ipynb
08-09-2020  11:29 PM           194,591 02-Conditional-Filtering.ipynb
13-08-2020  06:19 AM           196,385 03-Useful-Methods.ipynb
02-07-2020  04:02 AM            64,227 04-Missing-Data.ipynb
05-07-2020  01:58 AM           219,627 05-Groupby-Operations-and-MultiIndex.ipynb
17-05-2022  01:20 PM            62,978 06-Combining-DataFrames.ipynb
25-09-2020  11:34 PM            32,972 07-Text-Methods.ipynb
08-09-2020  11:29 PM            93,392 08-Time-Methods.ipynb
26-09-2020  05:18 AM            65,234 09-Inpu

In [40]:
df=pd.read_csv('tips.csv')

In [41]:
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [42]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [43]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [44]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [45]:
df.head(7)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5       25.29  4.71    Male     No  Sun  Dinner     4              6.32   
6        8.77  2.00    Male     No  Sun  Dinner     2              4.38   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251  
5          Erik Smith   213140353657882    Sun9679  
6  Kristopher Johnson  2223727524230344    Sun5985

In [46]:
df.tail(7)

total_bill   tip     sex smoker   day    time  size  price_per_person  \
237       32.83  1.17    Male    Yes   Sat  Dinner     2             16.42   
238       35.83  4.67  Female     No   Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

          Payer Name         CC Number Payment ID  
237     Thomas Brown  4284722681265508    Sat2929  
238   Kimberly Crane      676184013727    Sat9777  
239    Michael Avila  5296068606052842    Sat2657  
240   Monica Sanders  3506806155565404    Sat1766  
241       Keith Wong  6011891618747196    Sat3880  
242     Dennis Dixon     4375220550950      Sat17  
243  Michelle Hardin  3511451626698139    Thur672

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    int64  
 10  Payment ID        244 non-null    object 
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB


In [48]:
df.describe()

total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [49]:
df.describe().transpose()

count          mean           std           min  \
total_bill        244.0  1.978594e+01  8.902412e+00  3.070000e+00   
tip               244.0  2.998279e+00  1.383638e+00  1.000000e+00   
size              244.0  2.569672e+00  9.510998e-01  1.000000e+00   
price_per_person  244.0  7.888197e+00  2.914234e+00  2.880000e+00   
CC Number         244.0  2.563496e+15  2.369340e+15  6.040679e+10   

                           25%           50%           75%           max  
total_bill        1.334750e+01  1.779500e+01  2.412750e+01  5.081000e+01  
tip               2.000000e+00  2.900000e+00  3.562500e+00  1.000000e+01  
size              2.000000e+00  2.000000e+00  3.000000e+00  6.000000e+00  
price_per_person  5.800000e+00  7.255000e+00  9.390000e+00  2.027000e+01  
CC Number         3.040731e+13  3.525318e+15  4.553675e+15  6.596454e+15

### Columns

In [50]:
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [51]:
type(df['total_bill'])

pandas.core.series.Series

In [52]:
mycols=['total_bill','tip']
df[mycols]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [53]:
df[['total_bill','tip']]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [54]:
df['tip_percentage']=np.round((df['tip']/df['total_bill'])*100,decimals=2)

In [55]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  tip_percentage  
0  Christy Cunningham  3560325168603410    Sun2959            5.94  
1      Douglas Tucker  4478071379779230    Sun4608           16.05  
2      Travis Walters  6011812112971322    Sun4458           16.66  
3    Nathaniel Harris  4676137647685994    Sun5260           13.98  
4        Tonya Carter  4832732618637221    Sun2251           14.68

In [56]:
df.drop('tip_percentage',axis=1)

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [57]:
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  tip_percentage  
0    Christy Cunningham  3560325168603410    Sun2959            5.94  
1        Douglas Tucker  4478071379779230    Sun4608           16.05  
2        Travis Walters  6011812112971322    Sun4458           16.66  
3      Nathaniel Harris  4676137647685994    Sun5260           13.98  
4          Tonya Carter  4832732618637221    Sun2251           14.68  
..                  ...               ...        ...             ...  
239       Michael Avila  5296068606052842    Sat2657           20.39  
240      Monica Sanders  3506806155565404    Sat1766            7.36  
241          Keith Wong  6011891618747196    Sat3880            8.82  
242        Dennis Dixon     4375220550950      Sat17            9.82  
243     Michelle Hardin  3511451626698139    Thur672           15.97  

[244 rows x 12 columns]

In [58]:
df.drop('tip_percentage',axis=1,inplace=True)

In [59]:
df.head(7)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5       25.29  4.71    Male     No  Sun  Dinner     4              6.32   
6        8.77  2.00    Male     No  Sun  Dinner     2              4.38   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251  
5          Erik Smith   213140353657882    Sun9679  
6  Kristopher Johnson  2223727524230344    Sun5985

### Rows

In [60]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [61]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [62]:
df.set_index('Payment ID')

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun2959          16.99  1.01  Female     No   Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221  
...                      ...                 ...               ...  
Sat2657                 9.68       Michael Avila  5296068606052842  
Sat1766                13.59      Monica Sanders  3506806155565404  
Sat3880                11.34          Keith Wong  6011891618747196  
Sat17                   8.91        Dennis Dixon     4375220550950  
Thur672                 9.39     Michelle Hardin  3511451626698139  

[244 rows x 10 columns]

In [63]:
df.head(7)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5       25.29  4.71    Male     No  Sun  Dinner     4              6.32   
6        8.77  2.00    Male     No  Sun  Dinner     2              4.38   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251  
5          Erik Smith   213140353657882    Sun9679  
6  Kristopher Johnson  2223727524230344    Sun5985

In [64]:
df=df.set_index('Payment ID')

In [65]:
df

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun2959          16.99  1.01  Female     No   Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221  
...                      ...                 ...               ...  
Sat2657                 9.68       Michael Avila  5296068606052842  
Sat1766                13.59      Monica Sanders  3506806155565404  
Sat3880                11.34          Keith Wong  6011891618747196  
Sat17                   8.91        Dennis Dixon     4375220550950  
Thur672                 9.39     Michelle Hardin  3511451626698139  

[244 rows x 10 columns]

In [66]:
df.reset_index()

Payment ID  total_bill   tip     sex smoker   day    time  size  \
0      Sun2959       16.99  1.01  Female     No   Sun  Dinner     2   
1      Sun4608       10.34  1.66    Male     No   Sun  Dinner     3   
2      Sun4458       21.01  3.50    Male     No   Sun  Dinner     3   
3      Sun5260       23.68  3.31    Male     No   Sun  Dinner     2   
4      Sun2251       24.59  3.61  Female     No   Sun  Dinner     4   
..         ...         ...   ...     ...    ...   ...     ...   ...   
239    Sat2657       29.03  5.92    Male     No   Sat  Dinner     3   
240    Sat1766       27.18  2.00  Female    Yes   Sat  Dinner     2   
241    Sat3880       22.67  2.00    Male    Yes   Sat  Dinner     2   
242      Sat17       17.82  1.75    Male     No   Sat  Dinner     2   
243    Thur672       18.78  3.00  Female     No  Thur  Dinner     2   

     price_per_person          Payer Name         CC Number  
0                8.49  Christy Cunningham  3560325168603410  
1                3.45      Douglas Tucker  4478071379779230  
2                7.00      Travis Walters  6011812112971322  
3               11.84    Nathaniel Harris  4676137647685994  
4                6.15        Tonya Carter  4832732618637221  
..                ...                 ...               ...  
239              9.68       Michael Avila  5296068606052842  
240             13.59      Monica Sanders  3506806155565404  
241             11.34          Keith Wong  6011891618747196  
242              8.91        Dennis Dixon     4375220550950  
243              9.39     Michelle Hardin  3511451626698139  

[244 rows x 11 columns]

In [67]:
df.head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221

In [68]:
df=df.reset_index()
df

Payment ID  total_bill   tip     sex smoker   day    time  size  \
0      Sun2959       16.99  1.01  Female     No   Sun  Dinner     2   
1      Sun4608       10.34  1.66    Male     No   Sun  Dinner     3   
2      Sun4458       21.01  3.50    Male     No   Sun  Dinner     3   
3      Sun5260       23.68  3.31    Male     No   Sun  Dinner     2   
4      Sun2251       24.59  3.61  Female     No   Sun  Dinner     4   
..         ...         ...   ...     ...    ...   ...     ...   ...   
239    Sat2657       29.03  5.92    Male     No   Sat  Dinner     3   
240    Sat1766       27.18  2.00  Female    Yes   Sat  Dinner     2   
241    Sat3880       22.67  2.00    Male    Yes   Sat  Dinner     2   
242      Sat17       17.82  1.75    Male     No   Sat  Dinner     2   
243    Thur672       18.78  3.00  Female     No  Thur  Dinner     2   

     price_per_person          Payer Name         CC Number  
0                8.49  Christy Cunningham  3560325168603410  
1                3.45      Douglas Tucker  4478071379779230  
2                7.00      Travis Walters  6011812112971322  
3               11.84    Nathaniel Harris  4676137647685994  
4                6.15        Tonya Carter  4832732618637221  
..                ...                 ...               ...  
239              9.68       Michael Avila  5296068606052842  
240             13.59      Monica Sanders  3506806155565404  
241             11.34          Keith Wong  6011891618747196  
242              8.91        Dennis Dixon     4375220550950  
243              9.39     Michelle Hardin  3511451626698139  

[244 rows x 11 columns]

In [69]:
df=df.set_index('Payment ID')

In [70]:
df

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun2959          16.99  1.01  Female     No   Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221  
...                      ...                 ...               ...  
Sat2657                 9.68       Michael Avila  5296068606052842  
Sat1766                13.59      Monica Sanders  3506806155565404  
Sat3880                11.34          Keith Wong  6011891618747196  
Sat17                   8.91        Dennis Dixon     4375220550950  
Thur672                 9.39     Michelle Hardin  3511451626698139  

[244 rows x 10 columns]

In [71]:
df.iloc[0]

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [72]:
df.loc['Sun2959']

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [73]:
df.index

Index(['Sun2959', 'Sun4608', 'Sun4458', 'Sun5260', 'Sun2251', 'Sun9679',
       'Sun5985', 'Sun8157', 'Sun6820', 'Sun3775',
       ...
       'Sat7220', 'Sat4615', 'Sat5032', 'Sat2929', 'Sat9777', 'Sat2657',
       'Sat1766', 'Sat3880', 'Sat17', 'Thur672'],
      dtype='object', name='Payment ID', length=244)

In [74]:
df.iloc[0:4]

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994

In [75]:
df.loc[['Sun2959','Sun4608','Sun5260']]

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun5260                11.84    Nathaniel Harris  4676137647685994

In [76]:
df.drop('Sun2959',axis=0)

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
Sun9679          25.29  4.71    Male     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat2657          29.03  5.92    Male     No   Sat  Dinner     3   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   

            price_per_person        Payer Name         CC Number  
Payment ID                                                        
Sun4608                 3.45    Douglas Tucker  4478071379779230  
Sun4458                 7.00    Travis Walters  6011812112971322  
Sun5260                11.84  Nathaniel Harris  4676137647685994  
Sun2251                 6.15      Tonya Carter  4832732618637221  
Sun9679                 6.32        Erik Smith   213140353657882  
...                      ...               ...               ...  
Sat2657                 9.68     Michael Avila  5296068606052842  
Sat1766                13.59    Monica Sanders  3506806155565404  
Sat3880                11.34        Keith Wong  6011891618747196  
Sat17                   8.91      Dennis Dixon     4375220550950  
Thur672                 9.39   Michelle Hardin  3511451626698139  

[243 rows x 10 columns]

In [77]:
df.head()

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun2959          16.99  1.01  Female     No  Sun  Dinner     2   
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun2959                 8.49  Christy Cunningham  3560325168603410  
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221

In [78]:
df=df.drop('Sun2959',axis=0)

In [79]:
df.head(7)

total_bill   tip     sex smoker  day    time  size  \
Payment ID                                                       
Sun4608          10.34  1.66    Male     No  Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No  Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No  Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No  Sun  Dinner     4   
Sun9679          25.29  4.71    Male     No  Sun  Dinner     4   
Sun5985           8.77  2.00    Male     No  Sun  Dinner     2   
Sun8157          26.88  3.12    Male     No  Sun  Dinner     4   

            price_per_person          Payer Name         CC Number  
Payment ID                                                          
Sun4608                 3.45      Douglas Tucker  4478071379779230  
Sun4458                 7.00      Travis Walters  6011812112971322  
Sun5260                11.84    Nathaniel Harris  4676137647685994  
Sun2251                 6.15        Tonya Carter  4832732618637221  
Sun9679                 6.32          Erik Smith   213140353657882  
Sun5985                 4.38  Kristopher Johnson  2223727524230344  
Sun8157                 6.72         Robert Buck  3514785077705092

In [80]:
one_row=df.iloc[0]

In [81]:
one_row

total_bill                     10.34
tip                             1.66
sex                             Male
smoker                            No
day                              Sun
time                          Dinner
size                               3
price_per_person                3.45
Payer Name            Douglas Tucker
CC Number           4478071379779230
Name: Sun4608, dtype: object

# Inserting new Row

In [82]:
df=df.append(one_row)
df

total_bill   tip     sex smoker   day    time  size  \
Payment ID                                                        
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   
Sun4458          21.01  3.50    Male     No   Sun  Dinner     3   
Sun5260          23.68  3.31    Male     No   Sun  Dinner     2   
Sun2251          24.59  3.61  Female     No   Sun  Dinner     4   
Sun9679          25.29  4.71    Male     No   Sun  Dinner     4   
...                ...   ...     ...    ...   ...     ...   ...   
Sat1766          27.18  2.00  Female    Yes   Sat  Dinner     2   
Sat3880          22.67  2.00    Male    Yes   Sat  Dinner     2   
Sat17            17.82  1.75    Male     No   Sat  Dinner     2   
Thur672          18.78  3.00  Female     No  Thur  Dinner     2   
Sun4608          10.34  1.66    Male     No   Sun  Dinner     3   

            price_per_person        Payer Name         CC Number  
Payment ID                                                        
Sun4608                 3.45    Douglas Tucker  4478071379779230  
Sun4458                 7.00    Travis Walters  6011812112971322  
Sun5260                11.84  Nathaniel Harris  4676137647685994  
Sun2251                 6.15      Tonya Carter  4832732618637221  
Sun9679                 6.32        Erik Smith   213140353657882  
...                      ...               ...               ...  
Sat1766                13.59    Monica Sanders  3506806155565404  
Sat3880                11.34        Keith Wong  6011891618747196  
Sat17                   8.91      Dennis Dixon     4375220550950  
Thur672                 9.39   Michelle Hardin  3511451626698139  
Sun4608                 3.45    Douglas Tucker  4478071379779230  

[244 rows x 10 columns]

### Conditional Filtering

In [83]:
#country=['USA','CANADA','MEXICO']

data={'USA':{'Year':1776,'Pop':328,'GDP':20.5},'CANADA':{'Year':1867,'Pop':38,'GDP':1.7},'MEXICO':{'Year':1821,'Pop':126,'GDP':1.22}}

In [84]:
df=pd.DataFrame(data)

In [85]:
df=df.transpose()

In [86]:
df['Year']=df['Year'].astype(int)

In [87]:
df['Pop']=df['Pop'].astype(int)

In [88]:
df

Year  Pop    GDP
USA     1776  328  20.50
CANADA  1867   38   1.70
MEXICO  1821  126   1.22

In [89]:
df

Year  Pop    GDP
USA     1776  328  20.50
CANADA  1867   38   1.70
MEXICO  1821  126   1.22

In [90]:
df[df['Pop']>50]

Year  Pop    GDP
USA     1776  328  20.50
MEXICO  1821  126   1.22

In [91]:
df=pd.read_csv("tips.csv")

In [92]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [93]:
df[df['total_bill']>40]

total_bill    tip     sex smoker   day    time  size  price_per_person  \
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07   
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04   
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77   
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24   
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03   
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94   
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12   
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27   
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78   
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08   

          Payer Name         CC Number Payment ID  
59       Brian Ortiz  6596453823950595    Sat8139  
95     Aaron Bentley   180026611638690    Fri9628  
102    Heather Cohen   379771118886604    Sat6240  
142     Eric Andrews  4356531761046453   Thur3621  
156    Ryan Gonzales  3523151482063321    Sun7518  
170    Gregory Clark  5473850968388236    Sat1954  
182     Jose Parsons  4112207559459910    Sun2337  
184      Stephen Cox  3547798222044029    Sun5140  
197      Brooke Soto  5544902205760175   Thur9313  
212  Alex Williamson      676218815212    Sat4590

In [94]:
df[df['sex']=='Male']

total_bill   tip   sex smoker  day    time  size  price_per_person  \
1         10.34  1.66  Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50  Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31  Male     No  Sun  Dinner     2             11.84   
5         25.29  4.71  Male     No  Sun  Dinner     4              6.32   
6          8.77  2.00  Male     No  Sun  Dinner     2              4.38   
..          ...   ...   ...    ...  ...     ...   ...               ...   
236       12.60  1.00  Male    Yes  Sat  Dinner     2              6.30   
237       32.83  1.17  Male    Yes  Sat  Dinner     2             16.42   
239       29.03  5.92  Male     No  Sat  Dinner     3              9.68   
241       22.67  2.00  Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75  Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
5            Erik Smith   213140353657882    Sun9679  
6    Kristopher Johnson  2223727524230344    Sun5985  
..                  ...               ...        ...  
236       Matthew Myers  3543676378973965    Sat5032  
237        Thomas Brown  4284722681265508    Sat2929  
239       Michael Avila  5296068606052842    Sat2657  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[157 rows x 11 columns]

In [95]:
df[df['size']>3]

total_bill   tip     sex smoker   day    time  size  price_per_person  \
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
5         25.29  4.71    Male     No   Sun  Dinner     4              6.32   
7         26.88  3.12    Male     No   Sun  Dinner     4              6.72   
11        35.26  5.00  Female     No   Sun  Dinner     4              8.82   
13        18.43  3.00    Male     No   Sun  Dinner     4              4.61   
23        39.42  7.58    Male     No   Sat  Dinner     4              9.86   
25        17.81  2.34    Male     No   Sat  Dinner     4              4.45   
31        18.35  2.50    Male     No   Sat  Dinner     4              4.59   
33        20.69  2.45  Female     No   Sat  Dinner     4              5.17   
44        30.40  5.60    Male     No   Sun  Dinner     4              7.60   
47        32.40  6.00    Male     No   Sun  Dinner     4              8.10   
52        34.81  5.20  Female     No   Sun  Dinner     4              8.70   
54        25.56  4.34    Male     No   Sun  Dinner     4              6.39   
56        38.01  3.00    Male    Yes   Sat  Dinner     4              9.50   
59        48.27  6.73    Male     No   Sat  Dinner     4             12.07   
63        18.29  3.76    Male    Yes   Sat  Dinner     4              4.57   
77        27.20  4.00    Male     No  Thur   Lunch     4              6.80   
85        34.83  5.17  Female     No  Thur   Lunch     4              8.71   
95        40.17  4.73    Male    Yes   Fri  Dinner     4             10.04   
116       29.93  5.07    Male     No   Sun  Dinner     4              7.48   
119       24.08  2.92  Female     No  Thur   Lunch     4              6.02   
125       29.80  4.20  Female     No  Thur   Lunch     6              4.97   
141       34.30  6.70    Male     No  Thur   Lunch     6              5.72   
142       41.19  5.00    Male     No  Thur   Lunch     5              8.24   
143       27.05  5.00  Female     No  Thur   Lunch     6              4.51   
153       24.55  2.00    Male     No   Sun  Dinner     4              6.14   
154       19.77  2.00    Male     No   Sun  Dinner     4              4.94   
155       29.85  5.14  Female     No   Sun  Dinner     5              5.97   
156       48.17  5.00    Male     No   Sun  Dinner     6              8.03   
157       25.00  3.75  Female     No   Sun  Dinner     4              6.25   
159       16.49  2.00    Male     No   Sun  Dinner     4              4.12   
160       21.50  3.50    Male     No   Sun  Dinner     4              5.38   
167       31.71  4.50    Male     No   Sun  Dinner     4              7.93   
180       34.65  3.68    Male    Yes   Sun  Dinner     4              8.66   
183       23.17  6.50    Male    Yes   Sun  Dinner     4              5.79   
185       20.69  5.00    Male     No   Sun  Dinner     5              4.14   
187       30.46  2.00    Male    Yes   Sun  Dinner     5              6.09   
197       43.11  5.00  Female    Yes  Thur   Lunch     4             10.78   
204       20.53  4.00    Male    Yes  Thur   Lunch     4              5.13   
207       38.73  3.00    Male    Yes   Sat  Dinner     4              9.68   
211       25.89  5.16    Male    Yes   Sat  Dinner     4              6.47   
212       48.33  9.00    Male     No   Sat  Dinner     4             12.08   
216       28.15  3.00    Male    Yes   Sat  Dinner     5              5.63   
219       30.14  3.09  Female    Yes   Sat  Dinner     4              7.54   
227       20.45  3.00    Male     No   Sat  Dinner     4              5.11   
230       24.01  2.00    Male    Yes   Sat  Dinner     4              6.00   

                Payer Name         CC Number Payment ID  
4             Tonya Carter  4832732618637221    Sun2251  
5               Erik Smith   213140353657882    Sun9679  
7              Robert Buck  3514785077705092    Sun8157  
11            Diane Macias  4577817359320969    Sun6686  
13            Joshua Jones  6011163105616890    

In [96]:
df.head(7)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5       25.29  4.71    Male     No  Sun  Dinner     4              6.32   
6        8.77  2.00    Male     No  Sun  Dinner     2              4.38   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251  
5          Erik Smith   213140353657882    Sun9679  
6  Kristopher Johnson  2223727524230344    Sun5985

In [97]:
df[(df['total_bill']>30)  & (df['sex']=='Male')]

total_bill    tip   sex smoker   day    time  size  price_per_person  \
23        39.42   7.58  Male     No   Sat  Dinner     4              9.86   
39        31.27   5.00  Male     No   Sat  Dinner     3             10.42   
44        30.40   5.60  Male     No   Sun  Dinner     4              7.60   
47        32.40   6.00  Male     No   Sun  Dinner     4              8.10   
56        38.01   3.00  Male    Yes   Sat  Dinner     4              9.50   
59        48.27   6.73  Male     No   Sat  Dinner     4             12.07   
83        32.68   5.00  Male    Yes  Thur   Lunch     2             16.34   
95        40.17   4.73  Male    Yes   Fri  Dinner     4             10.04   
112       38.07   4.00  Male     No   Sun  Dinner     3             12.69   
141       34.30   6.70  Male     No  Thur   Lunch     6              5.72   
142       41.19   5.00  Male     No  Thur   Lunch     5              8.24   
156       48.17   5.00  Male     No   Sun  Dinner     6              8.03   
167       31.71   4.50  Male     No   Sun  Dinner     4              7.93   
170       50.81  10.00  Male    Yes   Sat  Dinner     3             16.94   
173       31.85   3.18  Male    Yes   Sun  Dinner     2             15.92   
175       32.90   3.11  Male    Yes   Sun  Dinner     2             16.45   
179       34.63   3.55  Male    Yes   Sun  Dinner     2             17.32   
180       34.65   3.68  Male    Yes   Sun  Dinner     4              8.66   
182       45.35   3.50  Male    Yes   Sun  Dinner     3             15.12   
184       40.55   3.00  Male    Yes   Sun  Dinner     2             20.27   
187       30.46   2.00  Male    Yes   Sun  Dinner     5              6.09   
207       38.73   3.00  Male    Yes   Sat  Dinner     4              9.68   
210       30.06   2.00  Male    Yes   Sat  Dinner     3             10.02   
212       48.33   9.00  Male     No   Sat  Dinner     4             12.08   
237       32.83   1.17  Male    Yes   Sat  Dinner     2             16.42   

                Payer Name         CC Number Payment ID  
23          Lance Peterson  3542584061609808     Sat239  
39       Mr. Brandon Berry  6011525851069856    Sat6373  
44             Todd Cooper      503846761263    Sun2274  
47            James Barnes  3552002592874186    Sun9677  
56   James Christensen DDS   349793629453226    Sat8903  
59             Brian Ortiz  6596453823950595    Sat8139  
83           Daniel Murphy  5356177501009133   Thur8801  
95           Aaron Bentley   180026611638690    Fri9628  
112             Jeff Lopez  3572865915176463     Sun591  
141         Steven Carlson  3526515703718508   Thur1025  
142           Eric Andrews  4356531761046453   Thur3621  
156          Ryan Gonzales  3523151482063321    Sun7518  
167         Michael Lawson  3566285921227119    Sun3719  
170          Gregory Clark  5473850968388236    Sat1954  
173            Scott Perez  3577115550328507    Sun9335  
175        Nathan Reynolds   370307040837149    Sun5109  
179           Brian Bailey   346656312114848    Sun9851  
180       James Hebert DDS      676168737648    Sun7544  
182           Jose Parsons  4112207559459910    Sun2337  
184            Stephen Cox  3547798222044029    Sun5140  
187          David Barrett  4792882899700988    Sun9987  
207          Ricky Ramirez   347817964484033    Sat4505  
210          Shawn Mendoza    30184049218122    Sat8361  
212        Alex Williamson      676218815212    Sat4590  
237           Thomas Brown  4284722681265508    Sat2929

In [98]:
df[(df['total_bill']>30) | (df['sex']=='Male')]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
1         10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
5         25.29  4.71    Male     No  Sun  Dinner     4              6.32   
6          8.77  2.00    Male     No  Sun  Dinner     2              4.38   
..          ...   ...     ...    ...  ...     ...   ...               ...   
237       32.83  1.17    Male    Yes  Sat  Dinner     2             16.42   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
5            Erik Smith   213140353657882    Sun9679  
6    Kristopher Johnson  2223727524230344    Sun5985  
..                  ...               ...        ...  
237        Thomas Brown  4284722681265508    Sat2929  
238      Kimberly Crane      676184013727    Sat9777  
239       Michael Avila  5296068606052842    Sat2657  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[164 rows x 11 columns]

In [99]:
df[(df['day']=='Sun') | (df['day']=='Sat')]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0         16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
..          ...   ...     ...    ...  ...     ...   ...               ...   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
238      Kimberly Crane      676184013727    Sat9777  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[163 rows x 11 columns]

In [100]:
options=['Sat','Sun']

In [101]:
df['day'].isin(options)

0       True
1       True
2       True
3       True
4       True
       ...  
239     True
240     True
241     True
242     True
243    False
Name: day, Length: 244, dtype: bool

In [102]:
df[df['day'].isin(options)]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0         16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
..          ...   ...     ...    ...  ...     ...   ...               ...   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
238      Kimberly Crane      676184013727    Sat9777  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[163 rows x 11 columns]

## Useful Methods
### Apply Methods - .apply()

In [103]:
def last_four(num):
    return str(num)[-4:]

In [104]:
last_four(123456789)

'6789'

In [105]:
df['Last_four_digits_of_CC']=df['CC Number'].apply(last_four)

In [106]:
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID Last_four_digits_of_CC  
0    Christy Cunningham  3560325168603410    Sun2959                   3410  
1        Douglas Tucker  4478071379779230    Sun4608                   9230  
2        Travis Walters  6011812112971322    Sun4458                   1322  
3      Nathaniel Harris  4676137647685994    Sun5260                   5994  
4          Tonya Carter  4832732618637221    Sun2251                   7221  
..                  ...               ...        ...                    ...  
239       Michael Avila  5296068606052842    Sat2657                   2842  
240      Monica Sanders  3506806155565404    Sat1766                   5404  
241          Keith Wong  6011891618747196    Sat3880                   7196  
242        Dennis Dixon     4375220550950      Sat17                   0950  
243     Michelle Hardin  3511451626698139    Thur672                   8139  

[244 rows x 12 columns]

In [107]:
df['CC Number'].apply(last_four)

0      3410
1      9230
2      1322
3      5994
4      7221
       ... 
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: object

In [108]:
df['total_bill'].mean()

19.785942622950824

In [109]:
def yelp(price):
    if price <10:
        return '$'
    elif price>=10 and price <30:
        return '$$'
    else:
        return '$$$'

In [110]:
df['yelp']=df['total_bill'].apply(yelp)

In [111]:
df['yelp']

0      $$
1      $$
2      $$
3      $$
4      $$
       ..
239    $$
240    $$
241    $$
242    $$
243    $$
Name: yelp, Length: 244, dtype: object

In [112]:
df.head(7)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5       25.29  4.71    Male     No  Sun  Dinner     4              6.32   
6        8.77  2.00    Male     No  Sun  Dinner     2              4.38   

           Payer Name         CC Number Payment ID Last_four_digits_of_CC yelp  
0  Christy Cunningham  3560325168603410    Sun2959                   3410   $$  
1      Douglas Tucker  4478071379779230    Sun4608                   9230   $$  
2      Travis Walters  6011812112971322    Sun4458                   1322   $$  
3    Nathaniel Harris  4676137647685994    Sun5260                   5994   $$  
4        Tonya Carter  4832732618637221    Sun2251                   7221   $$  
5          Erik Smith   213140353657882    Sun9679                   7882   $$  
6  Kristopher Johnson  2223727524230344    Sun5985                   0344    $

### .apply() with multiple columns
## Lambda Expression -

In [113]:
def simple(x):
    return x*2

In [114]:
simple(25)

50

In [115]:
lambda x:x*2

<function __main__.<lambda>(x)>

In [116]:
df['total_bill'].apply(simple)

0      33.98
1      20.68
2      42.02
3      47.36
4      49.18
       ...  
239    58.06
240    54.36
241    45.34
242    35.64
243    37.56
Name: total_bill, Length: 244, dtype: float64

In [117]:
df['total_bill'].apply(lambda x:x*2)

0      33.98
1      20.68
2      42.02
3      47.36
4      49.18
       ...  
239    58.06
240    54.36
241    45.34
242    35.64
243    37.56
Name: total_bill, Length: 244, dtype: float64

In [118]:
def quality(total_bill,tip):
    if tip/total_bill>0.25:
        return'Generous'
    else:
        return 'Other'

In [119]:
df['Quality']=df[['total_bill','tip']].apply(lambda df:quality(df['total_bill'],df['tip']),axis=1)

In [120]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID Last_four_digits_of_CC  \
0  Christy Cunningham  3560325168603410    Sun2959                   3410   
1      Douglas Tucker  4478071379779230    Sun4608                   9230   
2      Travis Walters  6011812112971322    Sun4458                   1322   
3    Nathaniel Harris  4676137647685994    Sun5260                   5994   
4        Tonya Carter  4832732618637221    Sun2251                   7221   

  yelp Quality  
0   $$   Other  
1   $$   Other  
2   $$   Other  
3   $$   Other  
4   $$   Other

In [121]:
df['Quality_Fast']=np.vectorize(quality)(df['total_bill'],df['tip'])

In [122]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID Last_four_digits_of_CC  \
0  Christy Cunningham  3560325168603410    Sun2959                   3410   
1      Douglas Tucker  4478071379779230    Sun4608                   9230   
2      Travis Walters  6011812112971322    Sun4458                   1322   
3    Nathaniel Harris  4676137647685994    Sun5260                   5994   
4        Tonya Carter  4832732618637221    Sun2251                   7221   

  yelp Quality Quality_Fast  
0   $$   Other        Other  
1   $$   Other        Other  
2   $$   Other        Other  
3   $$   Other        Other  
4   $$   Other        Other

In [123]:
%timeit df['Quality']=df[['total_bill','tip']].apply(lambda df:quality(df['total_bill'],df['tip']),axis=1)

4.25 ms ± 468 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [124]:
%timeit df['Quality_Fast']=np.vectorize(quality)(df['total_bill'],df['tip'])

306 µs ± 5.81 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [125]:
import timeit

In [126]:
setup='''
import numpy as np
import pandas as pd

df=pd.read_csv("tips.csv")

def quality(total_bill,tip):
    if tip/total_bill>0.25:
        return "Generous"
    else:
        return "Other"
'''

In [127]:
statement_one_lambda='''
df['Quality']=df[['total_bill','tip']].apply(lambda df:quality(df['total_bill'],df['tip']),axis=1)

'''

statement_two_vectorize='''
df['Quality_Fast']=np.vectorize(quality)(df['total_bill'],df['tip'])

'''

In [128]:
timeit.timeit(setup=setup,stmt=statement_one_lambda,number=1000)

3.9492227999999994

In [129]:
timeit.timeit(setup=setup,stmt=statement_two_vectorize,number=1000)

0.329199899999999

In [130]:
print("!! Jai Ganesh !!")

!! Jai Ganesh !!


### Describing and Sorting

In [131]:
df=pd.read_csv("tips.csv")

In [132]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [133]:
df.describe().transpose()

count          mean           std           min  \
total_bill        244.0  1.978594e+01  8.902412e+00  3.070000e+00   
tip               244.0  2.998279e+00  1.383638e+00  1.000000e+00   
size              244.0  2.569672e+00  9.510998e-01  1.000000e+00   
price_per_person  244.0  7.888197e+00  2.914234e+00  2.880000e+00   
CC Number         244.0  2.563496e+15  2.369340e+15  6.040679e+10   

                           25%           50%           75%           max  
total_bill        1.334750e+01  1.779500e+01  2.412750e+01  5.081000e+01  
tip               2.000000e+00  2.900000e+00  3.562500e+00  1.000000e+01  
size              2.000000e+00  2.000000e+00  3.000000e+00  6.000000e+00  
price_per_person  5.800000e+00  7.255000e+00  9.390000e+00  2.027000e+01  
CC Number         3.040731e+13  3.525318e+15  4.553675e+15  6.596454e+15

In [134]:
df.sort_values('tip',ascending=False)

total_bill    tip     sex smoker   day    time  size  price_per_person  \
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94   
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08   
23        39.42   7.58    Male     No   Sat  Dinner     4              9.86   
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07   
141       34.30   6.70    Male     No  Thur   Lunch     6              5.72   
..          ...    ...     ...    ...   ...     ...   ...               ...   
0         16.99   1.01  Female     No   Sun  Dinner     2              8.49   
236       12.60   1.00    Male    Yes   Sat  Dinner     2              6.30   
111        7.25   1.00  Female     No   Sat  Dinner     1              7.25   
67         3.07   1.00  Female    Yes   Sat  Dinner     1              3.07   
92         5.75   1.00  Female    Yes   Fri  Dinner     2              2.88   

             Payer Name         CC Number Payment ID  
170       Gregory Clark  5473850968388236    Sat1954  
212     Alex Williamson      676218815212    Sat4590  
23       Lance Peterson  3542584061609808     Sat239  
59          Brian Ortiz  6596453823950595    Sat8139  
141      Steven Carlson  3526515703718508   Thur1025  
..                  ...               ...        ...  
0    Christy Cunningham  3560325168603410    Sun2959  
236       Matthew Myers  3543676378973965    Sat5032  
111         Terri Jones  3559221007826887    Sat4801  
67        Tiffany Brock  4359488526995267    Sat3455  
92         Leah Ramirez  3508911676966392    Fri3780  

[244 rows x 11 columns]

In [135]:
df.sort_values(['tip','size'])

total_bill    tip     sex smoker   day    time  size  price_per_person  \
67         3.07   1.00  Female    Yes   Sat  Dinner     1              3.07   
111        7.25   1.00  Female     No   Sat  Dinner     1              7.25   
92         5.75   1.00  Female    Yes   Fri  Dinner     2              2.88   
236       12.60   1.00    Male    Yes   Sat  Dinner     2              6.30   
0         16.99   1.01  Female     No   Sun  Dinner     2              8.49   
..          ...    ...     ...    ...   ...     ...   ...               ...   
141       34.30   6.70    Male     No  Thur   Lunch     6              5.72   
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07   
23        39.42   7.58    Male     No   Sat  Dinner     4              9.86   
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08   
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94   

             Payer Name         CC Number Payment ID  
67        Tiffany Brock  4359488526995267    Sat3455  
111         Terri Jones  3559221007826887    Sat4801  
92         Leah Ramirez  3508911676966392    Fri3780  
236       Matthew Myers  3543676378973965    Sat5032  
0    Christy Cunningham  3560325168603410    Sun2959  
..                  ...               ...        ...  
141      Steven Carlson  3526515703718508   Thur1025  
59          Brian Ortiz  6596453823950595    Sat8139  
23       Lance Peterson  3542584061609808     Sat239  
212     Alex Williamson      676218815212    Sat4590  
170       Gregory Clark  5473850968388236    Sat1954  

[244 rows x 11 columns]

In [136]:
df['total_bill'].max()

50.81

In [137]:
df['total_bill'].idxmax()

170

In [138]:
df.iloc[170]

total_bill                     50.81
tip                             10.0
sex                             Male
smoker                           Yes
day                              Sat
time                          Dinner
size                               3
price_per_person               16.94
Payer Name             Gregory Clark
CC Number           5473850968388236
Payment ID                   Sat1954
Name: 170, dtype: object

In [139]:
df['total_bill'].min()

3.07

In [140]:
df['total_bill'].idxmin()

67

In [141]:
df.iloc[67]

total_bill                      3.07
tip                              1.0
sex                           Female
smoker                           Yes
day                              Sat
time                          Dinner
size                               1
price_per_person                3.07
Payer Name             Tiffany Brock
CC Number           4359488526995267
Payment ID                   Sat3455
Name: 67, dtype: object

In [142]:
df.iloc[df['total_bill'].idxmin()]

total_bill                      3.07
tip                              1.0
sex                           Female
smoker                           Yes
day                              Sat
time                          Dinner
size                               1
price_per_person                3.07
Payer Name             Tiffany Brock
CC Number           4359488526995267
Payment ID                   Sat3455
Name: 67, dtype: object

In [143]:
df.corr()

total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

In [144]:
df.head(7)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   
5       25.29  4.71    Male     No  Sun  Dinner     4              6.32   
6        8.77  2.00    Male     No  Sun  Dinner     2              4.38   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251  
5          Erik Smith   213140353657882    Sun9679  
6  Kristopher Johnson  2223727524230344    Sun5985

In [145]:
df['sex'].value_counts()

Male      157
Female     87
Name: sex, dtype: int64

In [146]:
df['day'].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [147]:
df['day'].nunique()

4

In [148]:
df['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

### Replace method

In [149]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [150]:
df['sex'].replace(['Female','Male'],['F','M'])

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

### Map

In [151]:
mymap={'Female':'F','Male':'M'}

In [152]:
df['sex'].map(mymap)

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

### Duplicates

In [153]:
simple_df=pd.DataFrame([1,2,3,3,3],['a','b','c','d','e'])

In [154]:
simple_df

0
a  1
b  2
c  3
d  3
e  3

In [155]:
simple_df.duplicated()

a    False
b    False
c    False
d     True
e     True
dtype: bool

In [156]:
simple_df.drop_duplicates()

0
a  1
b  2
c  3

### Between

In [157]:
df[df['total_bill'].between(10,20,inclusive=True)]

C:\Users\pkana\AppData\Local\Temp/ipykernel_8668/1152120679.py:1: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated infavour of `both` or `neither`.
  df[df['total_bill'].between(10,20,inclusive=True)]


total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
8         15.04  1.96    Male     No   Sun  Dinner     2              7.52   
9         14.78  3.23    Male     No   Sun  Dinner     2              7.39   
10        10.27  1.71    Male     No   Sun  Dinner     2              5.14   
..          ...   ...     ...    ...   ...     ...   ...               ...   
234       15.53  3.00    Male    Yes   Sat  Dinner     2              7.76   
235       10.07  1.25    Male     No   Sat  Dinner     2              5.04   
236       12.60  1.00    Male    Yes   Sat  Dinner     2              6.30   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
8       Joseph Mcdonald  3522866365840377    Sun6820  
9         Jerome Abbott  3532124519049786    Sun3775  
10        William Riley      566287581219    Sun2546  
..                  ...               ...        ...  
234       Tracy Douglas  4097938155941930    Sat7220  
235       Sean Gonzalez  3534021246117605    Sat4615  
236       Matthew Myers  3543676378973965    Sat5032  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[130 rows x 11 columns]

### nlargest

In [158]:
df.nlargest(2,'tip')

total_bill   tip   sex smoker  day    time  size  price_per_person  \
170       50.81  10.0  Male    Yes  Sat  Dinner     3             16.94   
212       48.33   9.0  Male     No  Sat  Dinner     4             12.08   

          Payer Name         CC Number Payment ID  
170    Gregory Clark  5473850968388236    Sat1954  
212  Alex Williamson      676218815212    Sat4590

In [159]:
df.nsmallest(5,'tip')

total_bill   tip     sex smoker  day    time  size  price_per_person  \
67         3.07  1.00  Female    Yes  Sat  Dinner     1              3.07   
92         5.75  1.00  Female    Yes  Fri  Dinner     2              2.88   
111        7.25  1.00  Female     No  Sat  Dinner     1              7.25   
236       12.60  1.00    Male    Yes  Sat  Dinner     2              6.30   
0         16.99  1.01  Female     No  Sun  Dinner     2              8.49   

             Payer Name         CC Number Payment ID  
67        Tiffany Brock  4359488526995267    Sat3455  
92         Leah Ramirez  3508911676966392    Fri3780  
111         Terri Jones  3559221007826887    Sat4801  
236       Matthew Myers  3543676378973965    Sat5032  
0    Christy Cunningham  3560325168603410    Sun2959

In [160]:
df.sort_values('tip',ascending=False)[:2]

total_bill   tip   sex smoker  day    time  size  price_per_person  \
170       50.81  10.0  Male    Yes  Sat  Dinner     3             16.94   
212       48.33   9.0  Male     No  Sat  Dinner     4             12.08   

          Payer Name         CC Number Payment ID  
170    Gregory Clark  5473850968388236    Sat1954  
212  Alex Williamson      676218815212    Sat4590

In [161]:
df.sort_values('tip',ascending=True)[:5]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
67         3.07  1.00  Female    Yes  Sat  Dinner     1              3.07   
236       12.60  1.00    Male    Yes  Sat  Dinner     2              6.30   
92         5.75  1.00  Female    Yes  Fri  Dinner     2              2.88   
111        7.25  1.00  Female     No  Sat  Dinner     1              7.25   
0         16.99  1.01  Female     No  Sun  Dinner     2              8.49   

             Payer Name         CC Number Payment ID  
67        Tiffany Brock  4359488526995267    Sat3455  
236       Matthew Myers  3543676378973965    Sat5032  
92         Leah Ramirez  3508911676966392    Fri3780  
111         Terri Jones  3559221007826887    Sat4801  
0    Christy Cunningham  3560325168603410    Sun2959

### Sampling

In [162]:
df.sample(5)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
169       10.63  2.00  Female    Yes  Sat  Dinner     2              5.32   
161       12.66  2.50    Male     No  Sun  Dinner     2              6.33   
69        15.01  2.09    Male    Yes  Sat  Dinner     2              7.50   
222        8.58  1.92    Male    Yes  Fri   Lunch     1              8.58   
93        16.32  4.30  Female    Yes  Fri  Dinner     2              8.16   

          Payer Name         CC Number Payment ID  
169         Amy Hill  3536332481454019    Sat1788  
161  Brandon Oconnor  4406882156920533    Sun5879  
69         Adam Hall  4700924377057571     Sat855  
222   Jason Lawrence  3505302934650403    Fri6624  
93    Natalie Nguyen  5181236182893396    Fri6963

In [163]:
#returns 10% sample from data
df.sample(frac=0.1)

total_bill   tip     sex smoker   day    time  size  price_per_person  \
32        15.06  3.00  Female     No   Sat  Dinner     2              7.53   
215       12.90  1.10  Female    Yes   Sat  Dinner     2              6.45   
213       13.27  2.50  Female    Yes   Sat  Dinner     2              6.64   
106       20.49  4.06    Male    Yes   Sat  Dinner     2             10.24   
143       27.05  5.00  Female     No  Thur   Lunch     6              4.51   
98        21.01  3.00    Male    Yes   Fri  Dinner     2             10.50   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
34        17.78  3.27    Male     No   Sat  Dinner     2              8.89   
18        16.97  3.50  Female     No   Sun  Dinner     3              5.66   
138       16.00  2.00    Male    Yes  Thur   Lunch     2              8.00   
127       14.52  2.00  Female     No  Thur   Lunch     2              7.26   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
182       45.35  3.50    Male    Yes   Sun  Dinner     3             15.12   
219       30.14  3.09  Female    Yes   Sat  Dinner     4              7.54   
201       12.74  2.01  Female    Yes  Thur   Lunch     2              6.37   
39        31.27  5.00    Male     No   Sat  Dinner     3             10.42   
123       15.95  2.00    Male     No  Thur   Lunch     2              7.98   
58        11.24  1.76    Male    Yes   Sat  Dinner     2              5.62   
62        11.02  1.98    Male    Yes   Sat  Dinner     2              5.51   
161       12.66  2.50    Male     No   Sun  Dinner     2              6.33   
177       14.48  2.00    Male    Yes   Sun  Dinner     2              7.24   
190       15.69  1.50    Male    Yes   Sun  Dinner     2              7.84   
225       16.27  2.50  Female    Yes   Fri   Lunch     2              8.14   
111        7.25  1.00  Female     No   Sat  Dinner     1              7.25   

            Payer Name         CC Number Payment ID  
32       Amanda Wilson   213186304291560    Sat1327  
215       Jessica Owen     4726904879471    Sat6983  
213     Robin Andersen      580140531089    Sat1374  
106      Karl Mcdaniel   180024452771522    Sat7865  
143       Regina Jones     4311048695487   Thur6179  
98          Michael Li  4831801127457917     Fri144  
4         Tonya Carter  4832732618637221    Sun2251  
34      Jacob Castillo  3551492000704805    Sat8124  
18      Laura Martinez    30422275171379    Sun2789  
138      Jason Burgess  3561461821942363   Thur2710  
127    Jessica Simmons   213102478792200   Thur1512  
2       Travis Walters  6011812112971322    Sun4458  
182       Jose Parsons  4112207559459910    Sun2337  
219       Shelby House      502097403252    Sat8863  
201      Abigail Parks  3586645396220590   Thur2544  
39   Mr. Brandon Berry  6011525851069856    Sat6373  
123   Christopher Lang  4820629318698319   Thur1992  
58       Troy Guerrero  3560782621035582    Sat6683  
62         Joseph Hart   180046232326178    Sat2265  
161    Brandon Oconnor  4406882156920533    Sun5879  
177        John Dudley  4565183162071073    Sun6203  
190       Riley Barnes   180053549128800    Sun5104  
225     Whitney Arnold  3579111947217428    Fri6665  
111        Terri Jones  3559221007826887    Sat4801

## Missing Data
    1. Keep the data
    2. Drop the data
    3. Fill the data

### 1. Keep the data

In [164]:
import pandas as pd
import numpy as np

In [165]:
np.nan

nan

In [166]:
pd.NA

<NA>

In [167]:
pd.NaT

NaT

In [168]:
np.nan == np.nan

False

In [169]:
np.nan is np.nan

True

In [170]:
myvar=np.nan

In [171]:
myvar is np.nan

True

In [172]:
myvar == np.nan

False

In [173]:
myvar is np.nan

True

In [174]:
df=pd.read_csv("movie_scores.csv")

In [175]:
df.head()

first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [176]:
df.isnull()

first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [177]:
df.notnull()

first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [178]:
df[df['pre_movie_score'].notnull()]

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [179]:
df[(df['pre_movie_score'].isnull()) & (df['first_name'].notnull())]

first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

### 2. Drop the data

In [180]:
df

first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [181]:
df.dropna()

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [182]:
df.dropna(thresh=1)

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [183]:
df.dropna(thresh=4)

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [184]:
df.dropna(thresh=5)

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [185]:
df

first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [186]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [187]:
df

first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [188]:
df.dropna()

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [189]:
df.dropna(subset=['post_movie_score'])

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [190]:
df.dropna(subset=['last_name'])

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [191]:
df.dropna(subset=['post_movie_score'],thresh=1)

first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

### 3. Fill the data

In [192]:
df

first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [193]:
df.fillna('NEW VALUE!')

first_name   last_name         age         sex pre_movie_score  \
0         Tom       Hanks        63.0           m             8.0   
1  NEW VALUE!  NEW VALUE!  NEW VALUE!  NEW VALUE!      NEW VALUE!   
2        Hugh     Jackman        51.0           m      NEW VALUE!   
3       Oprah     Winfrey        66.0           f             6.0   
4        Emma       Stone        31.0           f             7.0   

  post_movie_score  
0             10.0  
1       NEW VALUE!  
2       NEW VALUE!  
3              8.0  
4              9.0

In [194]:
df['pre_movie_score']=df['pre_movie_score'].fillna(0)

In [195]:
df

first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              0.0               NaN
2       Hugh   Jackman  51.0    m              0.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [196]:
df

first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              0.0               NaN
2       Hugh   Jackman  51.0    m              0.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [197]:
df=pd.read_csv('movie_scores.csv')

In [198]:
df['pre_movie_score'].fillna(df['pre_movie_score'].mean())

0    8.0
1    7.0
2    7.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [199]:
df.fillna(df.mean())

C:\Users\pkana\AppData\Local\Temp/ipykernel_8668/634187881.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean())


first_name last_name    age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.00    m              8.0              10.0
1        NaN       NaN  52.75  NaN              7.0               9.0
2       Hugh   Jackman  51.00    m              7.0               9.0
3      Oprah   Winfrey  66.00    f              6.0               8.0
4       Emma     Stone  31.00    f              7.0               9.0

In [200]:
airline_tix={'first':100,'business':np.nan,'economy_plus':50,'economy':30}

In [201]:
airline_tix

{'first': 100, 'business': nan, 'economy_plus': 50, 'economy': 30}

In [202]:
ser=pd.Series(airline_tix)

In [203]:
ser

first           100.0
business          NaN
economy_plus     50.0
economy          30.0
dtype: float64

In [204]:
ser.interpolate()

first           100.0
business         75.0
economy_plus     50.0
economy          30.0
dtype: float64

## Groupby Operations

In [205]:
df=pd.read_csv('mpg.csv')

In [206]:
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model_year  origin                       name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [207]:
df['model_year'].unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], dtype=int64)

In [208]:
df['model_year'].value_counts()

73    40
78    36
76    34
82    31
75    30
70    29
79    29
80    29
81    29
71    28
72    28
77    28
74    27
Name: model_year, dtype: int64

In [209]:
df.groupby('model_year').mean()['mpg']

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

In [210]:
df.groupby(['model_year','cylinders']).mean()

mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
70         4          25.285714    107.000000  2292.571429     16.000000   
           6          20.500000    199.000000  2710.500000     15.500000   
           8          14.111111    367.555556  3940.055556     11.194444   
71         4          27.461538    101.846154  2056.384615     16.961538   
           6          18.000000    243.375000  3171.875000     14.750000   
           8          13.428571    371.714286  4537.714286     12.214286   
72         3          19.000000     70.000000  2330.000000     13.500000   
           4          23.428571    111.535714  2382.642857     17.214286   
           8          13.615385    344.846154  4228.384615     13.000000   
73         3          18.000000     70.000000  2124.000000     13.500000   
           4          22.727273    109.272727  2338.090909     17.136364   
           6          19.000000    212.250000  2917.125000     15.687500   
           8          13.200000    365.250000  4279.050000     12.250000   
74         4          27.800000     96.533333  2151.466667     16.400000   
           6          17.857143    230.428571  3320.000000     16.857143   
           8          14.200000    315.200000  4438.400000     14.700000   
75         4          25.250000    114.833333  2489.250000     15.833333   
           6          17.583333    233.750000  3398.333333     17.708333   
           8          15.666667    330.500000  4108.833333     13.166667   
76         4          26.766667    106.333333  2306.600000     16.866667   
           6          20.000000    221.400000  3349.600000     17.000000   
           8          14.666667    324.000000  4064.666667     13.222222   
77         3          21.500000     80.000000  2720.000000     13.500000   
           4          29.107143    106.500000  2205.071429     16.064286   
           6          19.500000    220.400000  3383.000000     16.900000   
           8          16.000000    335.750000  4177.500000     13.662500   
78         4          29.576471    112.117647  2296.764706     16.282353   
           5          20.300000    131.000000  2830.000000     15.900000   
           6          19.066667    213.250000  3314.166667     16.391667   
           8          19.050000    300.833333  3563.333333     13.266667   
79         4          31.525000    113.583333  2357.583333     15.991667   
           5          25.400000    183.000000  3530.000000     20.100000   
           6          22.950000    205.666667  3025.833333     15.433333   
           8          18.630000    321.400000  3862.900000     15.400000   
80         3          23.700000     70.000000  2420.000000     12.500000   
           4          34.612000    111.000000  2360.080000     17.144000   
           5          36.400000    121.000000  2950.000000     19.900000   
           6          25.900000    196.500000  3145.500000     15.050000   
81         4          32.814286    108.857143  2275.476190     16.466667   
           6          23.428571    184.000000  3093.571429     15.442857   
           8          26.600000    350.000000  3725.000000     19.000000   
82         4          32.071429    118.571429  2402.321429     16.703571   
           6          28.333333    225.000000  2931.666667     16.033333   

                        origin  
model_year cylinders            
70         4          2.285714  
           6          1.000000  
           8          1.000000  
71         4          1.923077  
           6          1.000000  
           8          1.000000  
72         3          3.000000  
           4          1.928571  
           8          1.000000  
73         3          3.000000  
           4          2.000000  
           6          1.250000  
           8          1.000000  
74         4          2.200000  
           6          1.000000  
           8          1.000000  
75         4 

In [211]:
df.groupby(['model_year','cylinders']).mean().index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

In [212]:
df.groupby(['model_year','cylinders']).mean()['mpg']

model_year  cylinders
70          4            25.285714
            6            20.500000
            8            14.111111
71          4            27.461538
            6            18.000000
            8            13.428571
72          3            19.000000
            4            23.428571
            8            13.615385
73          3            18.000000
            4            22.727273
            6            19.000000
            8            13.200000
74          4            27.800000
            6            17.857143
            8            14.200000
75          4            25.250000
            6            17.583333
            8            15.666667
76          4            26.766667
            6            20.000000
            8            14.666667
77          3            21.500000
            4            29.107143
            6            19.500000
            8            16.000000
78          4            29.576471
            5            20.30000

In [213]:
df.groupby('model_year').describe().transpose()

model_year                   70           71           72           73  \
mpg          count    29.000000    28.000000    28.000000    40.000000   
             mean     17.689655    21.250000    18.714286    17.100000   
             std       5.339231     6.591942     5.435529     4.700245   
             min       9.000000    12.000000    11.000000    11.000000   
             25%      14.000000    15.500000    13.750000    13.000000   
             50%      16.000000    19.000000    18.500000    16.000000   
             75%      22.000000    27.000000    23.000000    20.000000   
             max      27.000000    35.000000    28.000000    29.000000   
cylinders    count    29.000000    28.000000    28.000000    40.000000   
             mean      6.758621     5.571429     5.821429     6.375000   
             std       1.724926     1.665079     2.073708     1.807215   
             min       4.000000     4.000000     3.000000     3.000000   
             25%       6.000000     4.000000     4.000000     4.000000   
             50%       8.000000     6.000000     4.000000     7.000000   
             75%       8.000000     6.500000     8.000000     8.000000   
             max       8.000000     8.000000     8.000000     8.000000   
displacement count    29.000000    28.000000    28.000000    40.000000   
             mean    281.413793   209.750000   218.375000   256.875000   
             std     124.421380   115.102410   123.781964   121.722085   
             min      97.000000    71.000000    70.000000    68.000000   
             25%     198.000000    97.750000   109.250000   121.750000   
             50%     307.000000   228.500000   131.000000   276.000000   
             75%     383.000000   273.000000   326.000000   350.250000   
             max     455.000000   400.000000   429.000000   455.000000   
weight       count    29.000000    28.000000    28.000000    40.000000   
             mean   3372.793103  2995.428571  3237.714286  3419.025000   
             std     852.868663  1061.830859   974.520960   974.809133   
             min    1835.000000  1613.000000  2100.000000  1867.000000   
             25%    2648.000000  2110.750000  2285.500000  2554.500000   
             50%    3449.000000  2798.000000  2956.000000  3338.500000   
             75%    4312.000000  3603.250000  4169.750000  4247.250000   
             max    4732.000000  5140.000000  4633.000000  4997.000000   
acceleration count    29.000000    28.000000    28.000000    40.000000   
             mean     12.948276    15.142857    15.125000    14.312500   
             std       3.330982     2.666171     2.850032     2.754222   
             min       8.000000    11.500000    11.000000     9.500000   
             25%      10.000000    13.375000    13.375000    12.500000   
             50%      12.500000    14.500000    14.500000    14.000000   
             75%      15.000000    16.125000    16.625000    16.000000   
             max      20.500000    20.500000    23.500000    21.000000   
origin       count    29.000000    28.000000    28.000000    40.000000   
             mean      1.310345     1.428571     1.535714     1.375000   
             std       0.603765     0.741798     0.792658     0.667467   
             min       1.000000     1.000000     1.000000     1.000000   
             25%       1.000000     1.000000     1.000000     1.000000   
             50%       1.000000     1.000000     1.000000     1.000000   
             75%       1.000000     2.000000     2.000000     2.000000   
             max       3.000000     3.000000     3.000000     3.000000   

model_year                   74           75           76           77  \
mpg          count    27.000000    30.000000    34.000000    28.000000   
             mean     22.703704    20.266667    21.573529    23.375000   
             std       6.420010     4.940566     5.889297     6.675862   
             min      13.000000    13.000000    13.000000    15.000000   
   

In [214]:
year_cyl=df.groupby(['model_year','cylinders']).mean()

In [215]:
year_cyl

mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
70         4          25.285714    107.000000  2292.571429     16.000000   
           6          20.500000    199.000000  2710.500000     15.500000   
           8          14.111111    367.555556  3940.055556     11.194444   
71         4          27.461538    101.846154  2056.384615     16.961538   
           6          18.000000    243.375000  3171.875000     14.750000   
           8          13.428571    371.714286  4537.714286     12.214286   
72         3          19.000000     70.000000  2330.000000     13.500000   
           4          23.428571    111.535714  2382.642857     17.214286   
           8          13.615385    344.846154  4228.384615     13.000000   
73         3          18.000000     70.000000  2124.000000     13.500000   
           4          22.727273    109.272727  2338.090909     17.136364   
           6          19.000000    212.250000  2917.125000     15.687500   
           8          13.200000    365.250000  4279.050000     12.250000   
74         4          27.800000     96.533333  2151.466667     16.400000   
           6          17.857143    230.428571  3320.000000     16.857143   
           8          14.200000    315.200000  4438.400000     14.700000   
75         4          25.250000    114.833333  2489.250000     15.833333   
           6          17.583333    233.750000  3398.333333     17.708333   
           8          15.666667    330.500000  4108.833333     13.166667   
76         4          26.766667    106.333333  2306.600000     16.866667   
           6          20.000000    221.400000  3349.600000     17.000000   
           8          14.666667    324.000000  4064.666667     13.222222   
77         3          21.500000     80.000000  2720.000000     13.500000   
           4          29.107143    106.500000  2205.071429     16.064286   
           6          19.500000    220.400000  3383.000000     16.900000   
           8          16.000000    335.750000  4177.500000     13.662500   
78         4          29.576471    112.117647  2296.764706     16.282353   
           5          20.300000    131.000000  2830.000000     15.900000   
           6          19.066667    213.250000  3314.166667     16.391667   
           8          19.050000    300.833333  3563.333333     13.266667   
79         4          31.525000    113.583333  2357.583333     15.991667   
           5          25.400000    183.000000  3530.000000     20.100000   
           6          22.950000    205.666667  3025.833333     15.433333   
           8          18.630000    321.400000  3862.900000     15.400000   
80         3          23.700000     70.000000  2420.000000     12.500000   
           4          34.612000    111.000000  2360.080000     17.144000   
           5          36.400000    121.000000  2950.000000     19.900000   
           6          25.900000    196.500000  3145.500000     15.050000   
81         4          32.814286    108.857143  2275.476190     16.466667   
           6          23.428571    184.000000  3093.571429     15.442857   
           8          26.600000    350.000000  3725.000000     19.000000   
82         4          32.071429    118.571429  2402.321429     16.703571   
           6          28.333333    225.000000  2931.666667     16.033333   

                        origin  
model_year cylinders            
70         4          2.285714  
           6          1.000000  
           8          1.000000  
71         4          1.923077  
           6          1.000000  
           8          1.000000  
72         3          3.000000  
           4          1.928571  
           8          1.000000  
73         3          3.000000  
           4          2.000000  
           6          1.250000  
           8          1.000000  
74         4          2.200000  
           6          1.000000  
           8          1.000000  
75         4 

In [216]:
year_cyl.index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

In [217]:
year_cyl.index.names

FrozenList(['model_year', 'cylinders'])

In [218]:
year_cyl.index.levels

FrozenList([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], [3, 4, 5, 6, 8]])

In [219]:
year_cyl.loc[70]

mpg  displacement       weight  acceleration    origin
cylinders                                                              
4          25.285714    107.000000  2292.571429     16.000000  2.285714
6          20.500000    199.000000  2710.500000     15.500000  1.000000
8          14.111111    367.555556  3940.055556     11.194444  1.000000

In [220]:
year_cyl.loc[[70,82]]

mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
70         4          25.285714    107.000000  2292.571429     16.000000   
           6          20.500000    199.000000  2710.500000     15.500000   
           8          14.111111    367.555556  3940.055556     11.194444   
82         4          32.071429    118.571429  2402.321429     16.703571   
           6          28.333333    225.000000  2931.666667     16.033333   

                        origin  
model_year cylinders            
70         4          2.285714  
           6          1.000000  
           8          1.000000  
82         4          1.714286  
           6          1.000000

In [221]:
year_cyl.loc[(70,8)]

mpg               14.111111
displacement     367.555556
weight          3940.055556
acceleration      11.194444
origin             1.000000
Name: (70, 8), dtype: float64

In [222]:
year_cyl.loc[[(70,8),(70,6),(82,4)]]

mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
70         8          14.111111    367.555556  3940.055556     11.194444   
           6          20.500000    199.000000  2710.500000     15.500000   
82         4          32.071429    118.571429  2402.321429     16.703571   

                        origin  
model_year cylinders            
70         8          1.000000  
           6          1.000000  
82         4          1.714286

In [223]:
df.groupby(['cylinders','model_year']).mean().loc[4]

mpg  displacement       weight  acceleration    origin
model_year                                                              
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

In [224]:
year_cyl.xs(key=4,level='cylinders')

mpg  displacement       weight  acceleration    origin
model_year                                                              
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

In [225]:
df.groupby(['cylinders','model_year']).mean().loc[[4,6]]

mpg  displacement       weight  acceleration  \
cylinders model_year                                                       
4         70          25.285714    107.000000  2292.571429     16.000000   
          71          27.461538    101.846154  2056.384615     16.961538   
          72          23.428571    111.535714  2382.642857     17.214286   
          73          22.727273    109.272727  2338.090909     17.136364   
          74          27.800000     96.533333  2151.466667     16.400000   
          75          25.250000    114.833333  2489.250000     15.833333   
          76          26.766667    106.333333  2306.600000     16.866667   
          77          29.107143    106.500000  2205.071429     16.064286   
          78          29.576471    112.117647  2296.764706     16.282353   
          79          31.525000    113.583333  2357.583333     15.991667   
          80          34.612000    111.000000  2360.080000     17.144000   
          81          32.814286    108.857143  2275.476190     16.466667   
          82          32.071429    118.571429  2402.321429     16.703571   
6         70          20.500000    199.000000  2710.500000     15.500000   
          71          18.000000    243.375000  3171.875000     14.750000   
          73          19.000000    212.250000  2917.125000     15.687500   
          74          17.857143    230.428571  3320.000000     16.857143   
          75          17.583333    233.750000  3398.333333     17.708333   
          76          20.000000    221.400000  3349.600000     17.000000   
          77          19.500000    220.400000  3383.000000     16.900000   
          78          19.066667    213.250000  3314.166667     16.391667   
          79          22.950000    205.666667  3025.833333     15.433333   
          80          25.900000    196.500000  3145.500000     15.050000   
          81          23.428571    184.000000  3093.571429     15.442857   
          82          28.333333    225.000000  2931.666667     16.033333   

                        origin  
cylinders model_year            
4         70          2.285714  
          71          1.923077  
          72          1.928571  
          73          2.000000  
          74          2.200000  
          75          2.166667  
          76          1.866667  
          77          1.857143  
          78          2.117647  
          79          1.583333  
          80          2.200000  
          81          2.095238  
          82          1.714286  
6         70          1.000000  
          71          1.000000  
          73          1.250000  
          74          1.000000  
          75          1.000000  
          76          1.300000  
          77          1.400000  
          78          1.166667  
          79          1.000000  
          80          2.000000  
          81          1.714286  
          82          1.000000

In [226]:
year_cyl

mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
70         4          25.285714    107.000000  2292.571429     16.000000   
           6          20.500000    199.000000  2710.500000     15.500000   
           8          14.111111    367.555556  3940.055556     11.194444   
71         4          27.461538    101.846154  2056.384615     16.961538   
           6          18.000000    243.375000  3171.875000     14.750000   
           8          13.428571    371.714286  4537.714286     12.214286   
72         3          19.000000     70.000000  2330.000000     13.500000   
           4          23.428571    111.535714  2382.642857     17.214286   
           8          13.615385    344.846154  4228.384615     13.000000   
73         3          18.000000     70.000000  2124.000000     13.500000   
           4          22.727273    109.272727  2338.090909     17.136364   
           6          19.000000    212.250000  2917.125000     15.687500   
           8          13.200000    365.250000  4279.050000     12.250000   
74         4          27.800000     96.533333  2151.466667     16.400000   
           6          17.857143    230.428571  3320.000000     16.857143   
           8          14.200000    315.200000  4438.400000     14.700000   
75         4          25.250000    114.833333  2489.250000     15.833333   
           6          17.583333    233.750000  3398.333333     17.708333   
           8          15.666667    330.500000  4108.833333     13.166667   
76         4          26.766667    106.333333  2306.600000     16.866667   
           6          20.000000    221.400000  3349.600000     17.000000   
           8          14.666667    324.000000  4064.666667     13.222222   
77         3          21.500000     80.000000  2720.000000     13.500000   
           4          29.107143    106.500000  2205.071429     16.064286   
           6          19.500000    220.400000  3383.000000     16.900000   
           8          16.000000    335.750000  4177.500000     13.662500   
78         4          29.576471    112.117647  2296.764706     16.282353   
           5          20.300000    131.000000  2830.000000     15.900000   
           6          19.066667    213.250000  3314.166667     16.391667   
           8          19.050000    300.833333  3563.333333     13.266667   
79         4          31.525000    113.583333  2357.583333     15.991667   
           5          25.400000    183.000000  3530.000000     20.100000   
           6          22.950000    205.666667  3025.833333     15.433333   
           8          18.630000    321.400000  3862.900000     15.400000   
80         3          23.700000     70.000000  2420.000000     12.500000   
           4          34.612000    111.000000  2360.080000     17.144000   
           5          36.400000    121.000000  2950.000000     19.900000   
           6          25.900000    196.500000  3145.500000     15.050000   
81         4          32.814286    108.857143  2275.476190     16.466667   
           6          23.428571    184.000000  3093.571429     15.442857   
           8          26.600000    350.000000  3725.000000     19.000000   
82         4          32.071429    118.571429  2402.321429     16.703571   
           6          28.333333    225.000000  2931.666667     16.033333   

                        origin  
model_year cylinders            
70         4          2.285714  
           6          1.000000  
           8          1.000000  
71         4          1.923077  
           6          1.000000  
           8          1.000000  
72         3          3.000000  
           4          1.928571  
           8          1.000000  
73         3          3.000000  
           4          2.000000  
           6          1.250000  
           8          1.000000  
74         4          2.200000  
           6          1.000000  
           8          1.000000  
75         4 

In [227]:
year_cyl.swaplevel()

mpg  displacement       weight  acceleration  \
cylinders model_year                                                       
4         70          25.285714    107.000000  2292.571429     16.000000   
6         70          20.500000    199.000000  2710.500000     15.500000   
8         70          14.111111    367.555556  3940.055556     11.194444   
4         71          27.461538    101.846154  2056.384615     16.961538   
6         71          18.000000    243.375000  3171.875000     14.750000   
8         71          13.428571    371.714286  4537.714286     12.214286   
3         72          19.000000     70.000000  2330.000000     13.500000   
4         72          23.428571    111.535714  2382.642857     17.214286   
8         72          13.615385    344.846154  4228.384615     13.000000   
3         73          18.000000     70.000000  2124.000000     13.500000   
4         73          22.727273    109.272727  2338.090909     17.136364   
6         73          19.000000    212.250000  2917.125000     15.687500   
8         73          13.200000    365.250000  4279.050000     12.250000   
4         74          27.800000     96.533333  2151.466667     16.400000   
6         74          17.857143    230.428571  3320.000000     16.857143   
8         74          14.200000    315.200000  4438.400000     14.700000   
4         75          25.250000    114.833333  2489.250000     15.833333   
6         75          17.583333    233.750000  3398.333333     17.708333   
8         75          15.666667    330.500000  4108.833333     13.166667   
4         76          26.766667    106.333333  2306.600000     16.866667   
6         76          20.000000    221.400000  3349.600000     17.000000   
8         76          14.666667    324.000000  4064.666667     13.222222   
3         77          21.500000     80.000000  2720.000000     13.500000   
4         77          29.107143    106.500000  2205.071429     16.064286   
6         77          19.500000    220.400000  3383.000000     16.900000   
8         77          16.000000    335.750000  4177.500000     13.662500   
4         78          29.576471    112.117647  2296.764706     16.282353   
5         78          20.300000    131.000000  2830.000000     15.900000   
6         78          19.066667    213.250000  3314.166667     16.391667   
8         78          19.050000    300.833333  3563.333333     13.266667   
4         79          31.525000    113.583333  2357.583333     15.991667   
5         79          25.400000    183.000000  3530.000000     20.100000   
6         79          22.950000    205.666667  3025.833333     15.433333   
8         79          18.630000    321.400000  3862.900000     15.400000   
3         80          23.700000     70.000000  2420.000000     12.500000   
4         80          34.612000    111.000000  2360.080000     17.144000   
5         80          36.400000    121.000000  2950.000000     19.900000   
6         80          25.900000    196.500000  3145.500000     15.050000   
4         81          32.814286    108.857143  2275.476190     16.466667   
6         81          23.428571    184.000000  3093.571429     15.442857   
8         81          26.600000    350.000000  3725.000000     19.000000   
4         82          32.071429    118.571429  2402.321429     16.703571   
6         82          28.333333    225.000000  2931.666667     16.033333   

                        origin  
cylinders model_year            
4         70          2.285714  
6         70          1.000000  
8         70          1.000000  
4         71          1.923077  
6         71          1.000000  
8         71          1.000000  
3         72          3.000000  
4         72          1.928571  
8         72          1.000000  
3         73          3.000000  
4         73          2.000000  
6         73          1.250000  
8         73          1.000000  
4         74          2.200000  
6         74          1.000000  
8         74          1.000000  
4         75 

In [228]:
df.groupby(['model_year','cylinders']).mean().swaplevel().loc[[4,6]].swaplevel()

mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
70         4          25.285714    107.000000  2292.571429     16.000000   
71         4          27.461538    101.846154  2056.384615     16.961538   
72         4          23.428571    111.535714  2382.642857     17.214286   
73         4          22.727273    109.272727  2338.090909     17.136364   
74         4          27.800000     96.533333  2151.466667     16.400000   
75         4          25.250000    114.833333  2489.250000     15.833333   
76         4          26.766667    106.333333  2306.600000     16.866667   
77         4          29.107143    106.500000  2205.071429     16.064286   
78         4          29.576471    112.117647  2296.764706     16.282353   
79         4          31.525000    113.583333  2357.583333     15.991667   
80         4          34.612000    111.000000  2360.080000     17.144000   
81         4          32.814286    108.857143  2275.476190     16.466667   
82         4          32.071429    118.571429  2402.321429     16.703571   
70         6          20.500000    199.000000  2710.500000     15.500000   
71         6          18.000000    243.375000  3171.875000     14.750000   
73         6          19.000000    212.250000  2917.125000     15.687500   
74         6          17.857143    230.428571  3320.000000     16.857143   
75         6          17.583333    233.750000  3398.333333     17.708333   
76         6          20.000000    221.400000  3349.600000     17.000000   
77         6          19.500000    220.400000  3383.000000     16.900000   
78         6          19.066667    213.250000  3314.166667     16.391667   
79         6          22.950000    205.666667  3025.833333     15.433333   
80         6          25.900000    196.500000  3145.500000     15.050000   
81         6          23.428571    184.000000  3093.571429     15.442857   
82         6          28.333333    225.000000  2931.666667     16.033333   

                        origin  
model_year cylinders            
70         4          2.285714  
71         4          1.923077  
72         4          1.928571  
73         4          2.000000  
74         4          2.200000  
75         4          2.166667  
76         4          1.866667  
77         4          1.857143  
78         4          2.117647  
79         4          1.583333  
80         4          2.200000  
81         4          2.095238  
82         4          1.714286  
70         6          1.000000  
71         6          1.000000  
73         6          1.250000  
74         6          1.000000  
75         6          1.000000  
76         6          1.300000  
77         6          1.400000  
78         6          1.166667  
79         6          1.000000  
80         6          2.000000  
81         6          1.714286  
82         6          1.000000

In [229]:
year_cyl.sort_index(level='cylinders',ascending=False)

mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
81         8          26.600000    350.000000  3725.000000     19.000000   
79         8          18.630000    321.400000  3862.900000     15.400000   
78         8          19.050000    300.833333  3563.333333     13.266667   
77         8          16.000000    335.750000  4177.500000     13.662500   
76         8          14.666667    324.000000  4064.666667     13.222222   
75         8          15.666667    330.500000  4108.833333     13.166667   
74         8          14.200000    315.200000  4438.400000     14.700000   
73         8          13.200000    365.250000  4279.050000     12.250000   
72         8          13.615385    344.846154  4228.384615     13.000000   
71         8          13.428571    371.714286  4537.714286     12.214286   
70         8          14.111111    367.555556  3940.055556     11.194444   
82         6          28.333333    225.000000  2931.666667     16.033333   
81         6          23.428571    184.000000  3093.571429     15.442857   
80         6          25.900000    196.500000  3145.500000     15.050000   
79         6          22.950000    205.666667  3025.833333     15.433333   
78         6          19.066667    213.250000  3314.166667     16.391667   
77         6          19.500000    220.400000  3383.000000     16.900000   
76         6          20.000000    221.400000  3349.600000     17.000000   
75         6          17.583333    233.750000  3398.333333     17.708333   
74         6          17.857143    230.428571  3320.000000     16.857143   
73         6          19.000000    212.250000  2917.125000     15.687500   
71         6          18.000000    243.375000  3171.875000     14.750000   
70         6          20.500000    199.000000  2710.500000     15.500000   
80         5          36.400000    121.000000  2950.000000     19.900000   
79         5          25.400000    183.000000  3530.000000     20.100000   
78         5          20.300000    131.000000  2830.000000     15.900000   
82         4          32.071429    118.571429  2402.321429     16.703571   
81         4          32.814286    108.857143  2275.476190     16.466667   
80         4          34.612000    111.000000  2360.080000     17.144000   
79         4          31.525000    113.583333  2357.583333     15.991667   
78         4          29.576471    112.117647  2296.764706     16.282353   
77         4          29.107143    106.500000  2205.071429     16.064286   
76         4          26.766667    106.333333  2306.600000     16.866667   
75         4          25.250000    114.833333  2489.250000     15.833333   
74         4          27.800000     96.533333  2151.466667     16.400000   
73         4          22.727273    109.272727  2338.090909     17.136364   
72         4          23.428571    111.535714  2382.642857     17.214286   
71         4          27.461538    101.846154  2056.384615     16.961538   
70         4          25.285714    107.000000  2292.571429     16.000000   
80         3          23.700000     70.000000  2420.000000     12.500000   
77         3          21.500000     80.000000  2720.000000     13.500000   
73         3          18.000000     70.000000  2124.000000     13.500000   
72         3          19.000000     70.000000  2330.000000     13.500000   

                        origin  
model_year cylinders            
81         8          1.000000  
79         8          1.000000  
78         8          1.000000  
77         8          1.000000  
76         8          1.000000  
75         8          1.000000  
74         8          1.000000  
73         8          1.000000  
72         8          1.000000  
71         8          1.000000  
70         8          1.000000  
82         6          1.000000  
81         6          1.714286  
80         6          2.000000  
79         6          1.000000  
78         6          1.166667  
77         6 

In [230]:
year_cyl.sort_index(level='model_year',ascending=False)

mpg  displacement       weight  acceleration  \
model_year cylinders                                                       
82         6          28.333333    225.000000  2931.666667     16.033333   
           4          32.071429    118.571429  2402.321429     16.703571   
81         8          26.600000    350.000000  3725.000000     19.000000   
           6          23.428571    184.000000  3093.571429     15.442857   
           4          32.814286    108.857143  2275.476190     16.466667   
80         6          25.900000    196.500000  3145.500000     15.050000   
           5          36.400000    121.000000  2950.000000     19.900000   
           4          34.612000    111.000000  2360.080000     17.144000   
           3          23.700000     70.000000  2420.000000     12.500000   
79         8          18.630000    321.400000  3862.900000     15.400000   
           6          22.950000    205.666667  3025.833333     15.433333   
           5          25.400000    183.000000  3530.000000     20.100000   
           4          31.525000    113.583333  2357.583333     15.991667   
78         8          19.050000    300.833333  3563.333333     13.266667   
           6          19.066667    213.250000  3314.166667     16.391667   
           5          20.300000    131.000000  2830.000000     15.900000   
           4          29.576471    112.117647  2296.764706     16.282353   
77         8          16.000000    335.750000  4177.500000     13.662500   
           6          19.500000    220.400000  3383.000000     16.900000   
           4          29.107143    106.500000  2205.071429     16.064286   
           3          21.500000     80.000000  2720.000000     13.500000   
76         8          14.666667    324.000000  4064.666667     13.222222   
           6          20.000000    221.400000  3349.600000     17.000000   
           4          26.766667    106.333333  2306.600000     16.866667   
75         8          15.666667    330.500000  4108.833333     13.166667   
           6          17.583333    233.750000  3398.333333     17.708333   
           4          25.250000    114.833333  2489.250000     15.833333   
74         8          14.200000    315.200000  4438.400000     14.700000   
           6          17.857143    230.428571  3320.000000     16.857143   
           4          27.800000     96.533333  2151.466667     16.400000   
73         8          13.200000    365.250000  4279.050000     12.250000   
           6          19.000000    212.250000  2917.125000     15.687500   
           4          22.727273    109.272727  2338.090909     17.136364   
           3          18.000000     70.000000  2124.000000     13.500000   
72         8          13.615385    344.846154  4228.384615     13.000000   
           4          23.428571    111.535714  2382.642857     17.214286   
           3          19.000000     70.000000  2330.000000     13.500000   
71         8          13.428571    371.714286  4537.714286     12.214286   
           6          18.000000    243.375000  3171.875000     14.750000   
           4          27.461538    101.846154  2056.384615     16.961538   
70         8          14.111111    367.555556  3940.055556     11.194444   
           6          20.500000    199.000000  2710.500000     15.500000   
           4          25.285714    107.000000  2292.571429     16.000000   

                        origin  
model_year cylinders            
82         6          1.000000  
           4          1.714286  
81         8          1.000000  
           6          1.714286  
           4          2.095238  
80         6          2.000000  
           5          2.000000  
           4          2.200000  
           3          3.000000  
79         8          1.000000  
           6          1.000000  
           5          2.000000  
           4          1.583333  
78         8          1.000000  
           6          1.166667  
           5          2.000000  
           4 

In [231]:
df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model_year  origin                       name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [232]:
df.agg({'mpg':['mean'],'cylinders':['max','std'],'weight':'min','acceleration':'std'})

mpg  cylinders  weight  acceleration
mean  23.514573        NaN     NaN           NaN
max         NaN   8.000000     NaN           NaN
std         NaN   1.701004     NaN      2.757689
min         NaN        NaN  1613.0           NaN

## Concatenation

In [233]:
data_one = {'A': ['A0', 'A1', 'A2', 'A3'],'B': ['B0', 'B1', 'B2', 'B3']}

In [234]:
data_two = {'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']}

In [235]:
one = pd.DataFrame(data_one)

In [236]:
two = pd.DataFrame(data_two)

In [237]:
one

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [238]:
two

C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [239]:
pd.concat([one,two],axis=1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [240]:
pd.concat([one,two],axis=0)

A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

In [241]:
one

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [242]:
two

C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [243]:
two.columns=one.columns

In [244]:
one

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [245]:
two

A   B
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [246]:
mydf=pd.concat([one,two],axis=0)

In [247]:
mydf.index=range(len(mydf))

In [248]:
mydf

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
4  C0  D0
5  C1  D1
6  C2  D2
7  C3  D3

## Merge
    1. Inner
    2. Outer
    3. Left or Right

In [249]:
regdt=[(1,'Andrew'),(2,'Bob'),(3,'Charlie'),(4,'Danny')]

In [250]:
logdt=[(2,'Andrew'),(3,'Bob'),(1,'Yolanda'),(4,'Xavier')]

In [251]:
reg=pd.DataFrame(columns=['reg_id','name'],index=range(len(regdt)))

In [252]:
log=pd.DataFrame(columns=['log_id','name'],index=range(len(logdt)))

In [253]:
reg

reg_id name
0    NaN  NaN
1    NaN  NaN
2    NaN  NaN
3    NaN  NaN

In [254]:
for i in regdt:
    reg.loc

In [255]:
for i in (range(len(regdt))):
    reg.iloc[i]=regdt[i]

In [256]:
for i in range(len(logdt)):
    log.iloc[i]=logdt[i]

In [257]:
reg

reg_id     name
0      1   Andrew
1      2      Bob
2      3  Charlie
3      4    Danny

In [258]:
log

log_id     name
0      2   Andrew
1      3      Bob
2      1  Yolanda
3      4   Xavier

In [259]:
reg.merge(log,how='inner',on='name')

reg_id    name log_id
0      1  Andrew      2
1      2     Bob      3

In [260]:
reg.merge(log,'outer','name')

reg_id     name log_id
0      1   Andrew      2
1      2      Bob      3
2      3  Charlie    NaN
3      4    Danny    NaN
4    NaN  Yolanda      1
5    NaN   Xavier      4

In [261]:
reg.merge(log,'left','name')

reg_id     name log_id
0      1   Andrew      2
1      2      Bob      3
2      3  Charlie    NaN
3      4    Danny    NaN

In [262]:
reg.merge(log,'right','name')

reg_id     name log_id
0      1   Andrew      2
1      2      Bob      3
2    NaN  Yolanda      1
3    NaN   Xavier      4

In [263]:
registrations = pd.DataFrame({'reg_id':[1,2,3,4],'name':['Andrew','Bobo','Claire','David']})
logins = pd.DataFrame({'log_id':[1,2,3,4],'name':['Xavier','Andrew','Yolanda','Bobo']})

In [264]:
registrations

reg_id    name
0       1  Andrew
1       2    Bobo
2       3  Claire
3       4   David

In [265]:
reg

reg_id     name
0      1   Andrew
1      2      Bob
2      3  Charlie
3      4    Danny

In [266]:
pd.merge(registrations,logins,how='inner',on='name')

reg_id    name  log_id
0       1  Andrew       2
1       2    Bobo       4

In [267]:
pd.merge(left=registrations,right=logins,how='left',on='name')

reg_id    name  log_id
0       1  Andrew     2.0
1       2    Bobo     4.0
2       3  Claire     NaN
3       4   David     NaN

In [268]:
pd.merge(left=registrations,right=logins,how='right',on='name')

reg_id     name  log_id
0     NaN   Xavier       1
1     1.0   Andrew       2
2     NaN  Yolanda       3
3     2.0     Bobo       4

In [269]:
pd.merge(left=registrations,right=logins,how='outer',on='name')

reg_id     name  log_id
0     1.0   Andrew     2.0
1     2.0     Bobo     4.0
2     3.0   Claire     NaN
3     4.0    David     NaN
4     NaN   Xavier     1.0
5     NaN  Yolanda     3.0

In [270]:
pd.merge(left=reg,right=log,how='outer',on='name')

reg_id     name log_id
0      1   Andrew      2
1      2      Bob      3
2      3  Charlie    NaN
3      4    Danny    NaN
4    NaN  Yolanda      1
5    NaN   Xavier      4

In [271]:
registrations=registrations.set_index('name')

In [272]:
registrations

reg_id
name          
Andrew       1
Bobo         2
Claire       3
David        4

In [273]:
pd.merge(registrations,logins,left_index=True,right_on='name',how='inner')

reg_id  log_id    name
1       1       2  Andrew
3       2       4    Bobo

In [274]:
registrations=registrations.reset_index()

In [275]:
registrations

name  reg_id
0  Andrew       1
1    Bobo       2
2  Claire       3
3   David       4

In [276]:
registrations.columns=['reg_name','reg_id']

In [277]:
registrations

reg_name  reg_id
0   Andrew       1
1     Bobo       2
2   Claire       3
3    David       4

In [278]:
logins

log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4     Bobo

In [279]:
pd.merge(registrations,logins,left_on='reg_name',right_on='name',how='inner')

reg_name  reg_id  log_id    name
0   Andrew       1       2  Andrew
1     Bobo       2       4    Bobo

In [280]:
result=pd.merge(registrations,logins,left_on='reg_name',right_on='name',how='inner')

In [281]:
result

reg_name  reg_id  log_id    name
0   Andrew       1       2  Andrew
1     Bobo       2       4    Bobo

In [282]:
result.drop('reg_name',axis=1,inplace=True)

In [283]:
registrations.columns=['name','id']

In [284]:
logins.columns=['id','name']

In [285]:
registrations

name  id
0  Andrew   1
1    Bobo   2
2  Claire   3
3   David   4

In [286]:
logins

id     name
0   1   Xavier
1   2   Andrew
2   3  Yolanda
3   4     Bobo

In [287]:
pd.merge(registrations,logins,how='inner',on='name')

name  id_x  id_y
0  Andrew     1     2
1    Bobo     2     4

In [288]:
pd.merge(registrations,logins,how='inner',on='name',suffixes=('_reg','_log'))

name  id_reg  id_log
0  Andrew       1       2
1    Bobo       2       4

## Text Methods

In [289]:
email='sagar@email.com'

In [290]:
email.split('@')

['sagar', 'email.com']

In [291]:
names=['andrew','bobo','claire','david','5']

In [292]:
names=pd.Series(['andrew','bobo','claire','david','5'])

In [293]:
names

0    andrew
1      bobo
2    claire
3     david
4         5
dtype: object

In [294]:
names.str.upper()

0    ANDREW
1      BOBO
2    CLAIRE
3     DAVID
4         5
dtype: object

In [295]:
names

0    andrew
1      bobo
2    claire
3     david
4         5
dtype: object

In [296]:
'5'.isdigit()

True

In [297]:
names.str.isdigit()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [298]:
tech_fin=pd.Series(['GOOG,APPL,AMZN','JPM,BAC,GS'])

In [299]:
tech_fin

0    GOOG,APPL,AMZN
1        JPM,BAC,GS
dtype: object

In [300]:
tech_fin=tech_fin.str.split(',')

In [301]:
tech_fin

0    [GOOG, APPL, AMZN]
1        [JPM, BAC, GS]
dtype: object

In [302]:
tech_fin.str[0]

0    GOOG
1     JPM
dtype: object

In [303]:
ticker=pd.Series(['GOOG,APPL,AMZN','JPM,BAC,GS'])

In [304]:
ticker.str.split(',',expand=True)

0     1     2
0  GOOG  APPL  AMZN
1   JPM   BAC    GS

In [305]:
messy_names=pd.Series(['sagar  ','bo;bo ','       andrew  '])

In [306]:
messy_names

0            sagar  
1             bo;bo 
2           andrew  
dtype: object

In [307]:
messy_names=messy_names.str.replace(';','')

In [308]:
messy_names=messy_names.str.strip()

In [309]:
messy_names

0     sagar
1      bobo
2    andrew
dtype: object

In [310]:
messy_names=messy_names.str.capitalize()
messy_names

0     Sagar
1      Bobo
2    Andrew
dtype: object

## DATE and TIME

In [311]:
from datetime import datetime

In [312]:
myyear=1993
mymonth=2
myday=22
myhour=16
mymin=55
mysec=21

In [313]:
mydate=datetime(myyear,mymonth,myday)

In [314]:
mydate

datetime.datetime(1993, 2, 22, 0, 0)

In [315]:
mydatetime=datetime(myyear,mymonth,myday,myhour,mymin,mysec)

In [316]:
mydatetime

datetime.datetime(1993, 2, 22, 16, 55, 21)

In [317]:
mydatetime.second

21

In [318]:
mydatetime.year

1993

In [319]:
myser=pd.Series(['Feb 22, 1993','2022-02-22',None])

In [320]:
myser

0    Feb 22, 1993
1      2022-02-22
2            None
dtype: object

In [321]:
timeser=pd.to_datetime(myser)

In [322]:
timeser[0].month

2

In [323]:
obvio_euro_date='31-12-2022'

In [324]:
obvio_euro_date1=pd.to_datetime(obvio_euro_date)
obvio_euro_date1

Timestamp('2022-12-31 00:00:00')

In [325]:
#Here also month is different
obvio_euro_date1.month

12

In [326]:
euro_date='10-12-2022'
pd.to_datetime(euro_date)

Timestamp('2022-10-12 00:00:00')

In [327]:
euro_date1=pd.to_datetime(euro_date)
euro_date1

Timestamp('2022-10-12 00:00:00')

In [328]:
#here month is different
euro_date1.month

10

In [329]:
#to solve this problem

obvio_euro_date2=pd.to_datetime(obvio_euro_date,dayfirst=True)
euro_date2=pd.to_datetime(euro_date,dayfirst=True)

In [330]:
obvio_euro_date2

Timestamp('2022-12-31 00:00:00')

In [331]:
euro_date2

Timestamp('2022-12-10 00:00:00')

In [332]:
obvio_euro_date2.month

12

In [333]:
euro_date2.month

12

In [334]:
styledate='12--Dec--2000'

In [335]:
pd.to_datetime(styledate,format='%d--%b--%Y')

Timestamp('2000-12-12 00:00:00')

In [336]:
customedate="12th Dec 2000"

In [337]:
customedate1=pd.to_datetime(customedate)

In [338]:
customedate1.month

12

In [339]:
sales=pd.read_csv("RetailSales_BeerWineLiquor.csv")

In [340]:
sales

DATE  MRTSSM4453USN
0    1992-01-01           1509
1    1992-02-01           1541
2    1992-03-01           1597
3    1992-04-01           1675
4    1992-05-01           1822
..          ...            ...
335  2019-12-01           6630
336  2020-01-01           4388
337  2020-02-01           4533
338  2020-03-01           5562
339  2020-04-01           5207

[340 rows x 2 columns]

In [341]:
sales['DATE']

0      1992-01-01
1      1992-02-01
2      1992-03-01
3      1992-04-01
4      1992-05-01
          ...    
335    2019-12-01
336    2020-01-01
337    2020-02-01
338    2020-03-01
339    2020-04-01
Name: DATE, Length: 340, dtype: object

In [342]:
sales['DATE']=pd.to_datetime(sales['DATE'])

In [343]:
sales

DATE  MRTSSM4453USN
0   1992-01-01           1509
1   1992-02-01           1541
2   1992-03-01           1597
3   1992-04-01           1675
4   1992-05-01           1822
..         ...            ...
335 2019-12-01           6630
336 2020-01-01           4388
337 2020-02-01           4533
338 2020-03-01           5562
339 2020-04-01           5207

[340 rows x 2 columns]

In [344]:
sales['DATE'][0].year

1992

In [345]:

sales=pd.read_csv('RetailSales_BeerWineLiquor.csv',parse_dates=[0]) #[0] because date in 0th column

In [346]:
sales['DATE'][0].year

1992

In [347]:
sales=pd.read_csv('RetailSales_BeerWineLiquor.csv',parse_dates=[0])

In [348]:
sales=sales.set_index('DATE')

In [349]:
sales.resample(rule='A').mean() #list of rule is in pandas documentation

MRTSSM4453USN
DATE                     
1992-12-31    1807.250000
1993-12-31    1794.833333
1994-12-31    1841.750000
1995-12-31    1833.916667
1996-12-31    1929.750000
1997-12-31    2006.750000
1998-12-31    2115.166667
1999-12-31    2206.333333
2000-12-31    2375.583333
2001-12-31    2468.416667
2002-12-31    2491.166667
2003-12-31    2539.083333
2004-12-31    2682.416667
2005-12-31    2797.250000
2006-12-31    3001.333333
2007-12-31    3177.333333
2008-12-31    3292.000000
2009-12-31    3353.750000
2010-12-31    3450.083333
2011-12-31    3532.666667
2012-12-31    3697.083333
2013-12-31    3839.666667
2014-12-31    4023.833333
2015-12-31    4212.500000
2016-12-31    4434.416667
2017-12-31    4602.666667
2018-12-31    4830.666667
2019-12-31    4972.750000
2020-12-31    4922.500000

In [350]:
sales=pd.read_csv('RetailSales_BeerWineLiquor.csv',parse_dates=[0]) #[0] because date in 0th column

In [351]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   DATE           340 non-null    datetime64[ns]
 1   MRTSSM4453USN  340 non-null    int64         
dtypes: datetime64[ns](1), int64(1)
memory usage: 5.4 KB


In [352]:
sales['DATE']

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...    
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[ns]

In [353]:
sales['DATE'].dt.year

0      1992
1      1992
2      1992
3      1992
4      1992
       ... 
335    2019
336    2020
337    2020
338    2020
339    2020
Name: DATE, Length: 340, dtype: int64

In [354]:
sales['DATE'].dt.month

0       1
1       2
2       3
3       4
4       5
       ..
335    12
336     1
337     2
338     3
339     4
Name: DATE, Length: 340, dtype: int64

## Reading Files

In [355]:
pwd

'C:\\Users\\pkana\\Pierian Data Inc\\Python for Machine Learning & Data Science Masterclass\\03-Pandas'

In [356]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 1C0B-77D4

 Directory of C:\Users\pkana\Pierian Data Inc\Python for Machine Learning & Data Science Masterclass\03-Pandas

18-05-2022  12:02 PM    <DIR>          .
12-05-2022  11:52 AM    <DIR>          ..
13-05-2022  12:01 PM    <DIR>          .ipynb_checkpoints
13-07-2020  12:37 AM    <DIR>          __pycache__
13-05-2022  05:59 PM           565,402 00-Series.ipynb
08-09-2020  11:29 PM           208,957 01-DataFrames.ipynb
08-09-2020  11:29 PM           194,591 02-Conditional-Filtering.ipynb
13-08-2020  06:19 AM           196,385 03-Useful-Methods.ipynb
02-07-2020  04:02 AM            64,227 04-Missing-Data.ipynb
05-07-2020  01:58 AM           219,627 05-Groupby-Operations-and-MultiIndex.ipynb
17-05-2022  01:20 PM            62,978 06-Combining-DataFrames.ipynb
25-09-2020  11:34 PM            32,972 07-Text-Methods.ipynb
08-09-2020  11:29 PM            93,392 08-Time-Methods.ipynb
26-09-2020  05:18 AM            65,234 09-Inpu

In [357]:
import os

In [358]:
os.getcwd()

'C:\\Users\\pkana\\Pierian Data Inc\\Python for Machine Learning & Data Science Masterclass\\03-Pandas'

### .CSV

In [359]:
#CSV

df=pd.read_csv("example.csv",header=None)

In [360]:
df

0   1   2   3
0   a   b   c   d
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15

In [361]:
df=pd.read_csv("example.csv",index_col=0)

In [362]:
df

b   c   d
a             
0    1   2   3
4    5   6   7
8    9  10  11
12  13  14  15

In [363]:
df

b   c   d
a             
0    1   2   3
4    5   6   7
8    9  10  11
12  13  14  15

In [364]:
df.to_csv("newfile.csv",index=False)

In [365]:
pd.read_csv("new_file.csv")

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### .HTML

In [366]:
url="https://en.wikipedia.org/wiki/World_population"

In [367]:
tables=pd.read_html(url)

In [368]:
len(tables)

26

In [371]:
tables[0]['2000']

0                                                  1270
1                                                  1053
2                                                   283
3                                                   212
4                                                   136
5                                                   176
6                                                   123
7                                                   131
8                                                   146
9                                                   103
10                                                 6127
11    Notes: .mw-parser-output .reflist{font-size:90...
Name: 2000, dtype: object

In [373]:
worldtopten=tables[0]

In [375]:
worldtopten.drop('#',axis=1,inplace=True)

In [376]:
worldtopten.columns=['Country','2000','2015','2030 Est.']

In [384]:
worldtopten.drop(index=11,axis=0,inplace=True)

In [385]:
worldtopten

Country  2000  2015 2030 Est.
0        China[B]  1270  1376      1416
1           India  1053  1311      1528
2   United States   283   322       356
3       Indonesia   212   258       295
4        Pakistan   136   208       245
5          Brazil   176   206       228
6         Nigeria   123   182       263
7      Bangladesh   131   161       186
8          Russia   146   146       149
9          Mexico   103   127       148
10    World total  6127  7349      8501

In [386]:
tables[5]

Rank      Country  Population  Area(km2)  Density(pop/km2)
0     1    Singapore     5704000        710              8033
1     2   Bangladesh   172720000     143998              1199
2     3    Palestine     5266785       6020               847
3     4      Lebanon     6856000      10452               656
4     5       Taiwan    23604000      36193               652
5     6  South Korea    51781000      99538               520
6     7       Rwanda    12374000      26338               470
7     8        Haiti    11578000      27065               428
8     9  Netherlands    17720000      41526               427
9    10       Israel     9520000      22072               431

In [387]:
worldtopten.to_html('sampletable.html',index=False)

In [388]:
worldtopten

Country  2000  2015 2030 Est.
0        China[B]  1270  1376      1416
1           India  1053  1311      1528
2   United States   283   322       356
3       Indonesia   212   258       295
4        Pakistan   136   208       245
5          Brazil   176   206       228
6         Nigeria   123   182       263
7      Bangladesh   131   161       186
8          Russia   146   146       149
9          Mexico   103   127       148
10    World total  6127  7349      8501

## Reading Excel file

In [392]:
df=pd.read_excel('my_excel_file.xlsx',sheet_name='First_Sheet')

In [393]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [394]:
#to list oll the sheet names in excelfile

wb=pd.ExcelFile('my_excel_file.xlsx')

In [396]:
wb.sheet_names

['First_Sheet']

In [402]:
excel_sheet_dict=pd.read_excel('my_excel_file.xlsx')

In [403]:
type(excel_sheet_dict)

#here type is dataframe 

pandas.core.frame.DataFrame

In [405]:
excel_sheet_dict=pd.read_excel('my_excel_file.xlsx',sheet_name=None)

In [406]:
type(excel_sheet_dict)

#when sheet_name is 'None' type becomes dictionary

dict

In [401]:
excel_sheet_dict.keys()

dict_keys(['First_Sheet'])

In [409]:
df=excel_sheet_dict['First_Sheet']

In [408]:
excel_sheet_dict

{'First_Sheet':     a   b   c   d
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15}

In [411]:
df.to_excel('example111.xlsx',sheet_name='hello')

## Reading through SQL Database

In [412]:
from sqlalchemy import create_engine

In [413]:
temp_db=create_engine('sqlite:///:memory:')

In [414]:
pd.DataFrame(data=np.random.randint(low=0,high=100,size=(4,4)),columns=['a','b','c','d'])

a   b   c   d
0   4   0  12  90
1   2   7  44  54
2  49  76  98   3
3  32  91  43   7

In [415]:
df.to_sql(name='new_table',con=temp_db)

In [416]:
new_df=pd.read_sql(sql='new_table',con=temp_db)

In [417]:
new_df

index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15

In [419]:
result=pd.read_sql_query(sql='SELECT a,c FROM new_table',con=temp_db)

In [420]:
result

a   c
0   0   2
1   4   6
2   8  10
3  12  14

In [421]:
from sqlalchemy import create_engine

In [423]:
temp_db1=create_engine('sqlite:///:memory:')

In [426]:
df=pd.DataFrame(data=np.random.randint(1,21,(4,4)),columns=['a','b','c','d'])

In [427]:
df.to_sql(name='newnewtable',con=temp_db1)

In [430]:
newdf=pd.read_sql(sql='newnewtable',con=temp_db1)

In [432]:
result1=pd.read_sql_query(sql="SELECT a,d FROM newnewtable",con=temp_db1)

In [433]:
result1

a   d
0  11   6
1   3  15
2  11  10
3  19  19

## .pivot() & .pivot_table()

In [435]:
df=pd.read_csv('Sales_Funnel_CRM.csv')

In [436]:
df.head()

Account Number  Company      Contact Account Manager     Product  Licenses  \
0         2123398   Google  Larry Pager    Edward Thorp   Analytics       150   
1         2123398   Google  Larry Pager    Edward Thorp  Prediction       150   
2         2123398   Google  Larry Pager    Edward Thorp    Tracking       300   
3         2192650     BOBO  Larry Pager    Edward Thorp   Analytics       150   
4          420496     IKEA    Elon Tusk    Edward Thorp   Analytics       300   

   Sale Price        Status  
0     2100000     Presented  
1      700000     Presented  
2      350000  Under Review  
3     2450000          Lost  
4     4550000           Won

In [437]:
df.pivot(index='Company',columns='Product',values='Licenses')

Product       Analytics  GPS Positioning  Prediction  Tracking
Company                                                       
 Google           150.0              NaN       150.0     300.0
ATT                 NaN              NaN       150.0     150.0
Apple             300.0              NaN         NaN       NaN
BOBO              150.0              NaN         NaN       NaN
CVS Health          NaN              NaN         NaN     450.0
Cisco             300.0            300.0         NaN       NaN
Exxon Mobile      150.0              NaN         NaN       NaN
IKEA              300.0              NaN         NaN       NaN
Microsoft           NaN              NaN         NaN     300.0
Salesforce        750.0              NaN         NaN       NaN
Tesla Inc.        300.0              NaN       150.0       NaN
Walmart           150.0              NaN         NaN       NaN

In [439]:
licenses=df[['Company','Product','Licenses']]

In [440]:
licenses

Company          Product  Licenses
0         Google        Analytics       150
1         Google       Prediction       150
2         Google         Tracking       300
3           BOBO        Analytics       150
4           IKEA        Analytics       300
5     Tesla Inc.        Analytics       300
6     Tesla Inc.       Prediction       150
7      Microsoft         Tracking       300
8        Walmart        Analytics       150
9          Apple        Analytics       300
10  Exxon Mobile        Analytics       150
11           ATT         Tracking       150
12           ATT       Prediction       150
13    CVS Health         Tracking       450
14    Salesforce        Analytics       750
15         Cisco        Analytics       300
16         Cisco  GPS Positioning       300

In [441]:
pd.pivot(data=licenses,index='Company',columns='Product',values='Licenses')

Product       Analytics  GPS Positioning  Prediction  Tracking
Company                                                       
 Google           150.0              NaN       150.0     300.0
ATT                 NaN              NaN       150.0     150.0
Apple             300.0              NaN         NaN       NaN
BOBO              150.0              NaN         NaN       NaN
CVS Health          NaN              NaN         NaN     450.0
Cisco             300.0            300.0         NaN       NaN
Exxon Mobile      150.0              NaN         NaN       NaN
IKEA              300.0              NaN         NaN       NaN
Microsoft           NaN              NaN         NaN     300.0
Salesforce        750.0              NaN         NaN       NaN
Tesla Inc.        300.0              NaN       150.0       NaN
Walmart           150.0              NaN         NaN       NaN

In [458]:
pivoteddf=df.groupby(['Product','Company']).sum()['Licenses']

In [459]:
pivoteddf

Product          Company     
Analytics         Google         150
                 Apple           300
                 BOBO            150
                 Cisco           300
                 Exxon Mobile    150
                 IKEA            300
                 Salesforce      750
                 Tesla Inc.      300
                 Walmart         150
GPS Positioning  Cisco           300
Prediction        Google         150
                 ATT             150
                 Tesla Inc.      150
Tracking          Google         300
                 ATT             150
                 CVS Health      450
                 Microsoft       300
Name: Licenses, dtype: int64

In [460]:
pd.pivot_table(data=df,index='Company',aggfunc='sum')

Account Number  Licenses  Sale Price
Company                                           
 Google              6370194       600     3150000
ATT                  1396064       300     1050000
Apple                 405886       300     4550000
BOBO                 2192650       150     2450000
CVS Health            902797       450      490000
Cisco                4338998       600     4900000
Exxon Mobile          470248       150     2100000
IKEA                  420496       300     4550000
Microsoft            1216870       300      350000
Salesforce           2046943       750     7000000
Tesla Inc.           1273370       450     3500000
Walmart              2200450       150     2450000

In [461]:
df.groupby('Company').sum()

Account Number  Licenses  Sale Price
Company                                           
 Google              6370194       600     3150000
ATT                  1396064       300     1050000
Apple                 405886       300     4550000
BOBO                 2192650       150     2450000
CVS Health            902797       450      490000
Cisco                4338998       600     4900000
Exxon Mobile          470248       150     2100000
IKEA                  420496       300     4550000
Microsoft            1216870       300      350000
Salesforce           2046943       750     7000000
Tesla Inc.           1273370       450     3500000
Walmart              2200450       150     2450000

In [462]:
pd.pivot_table(data=df,index='Company',aggfunc='sum',values=['Licenses','Sale Price'])

Licenses  Sale Price
Company                           
 Google            600     3150000
ATT                300     1050000
Apple              300     4550000
BOBO               150     2450000
CVS Health         450      490000
Cisco              600     4900000
Exxon Mobile       150     2100000
IKEA               300     4550000
Microsoft          300      350000
Salesforce         750     7000000
Tesla Inc.         450     3500000
Walmart            150     2450000

In [463]:
df

Account Number       Company       Contact Account Manager  \
0          2123398        Google   Larry Pager    Edward Thorp   
1          2123398        Google   Larry Pager    Edward Thorp   
2          2123398        Google   Larry Pager    Edward Thorp   
3          2192650          BOBO   Larry Pager    Edward Thorp   
4           420496          IKEA     Elon Tusk    Edward Thorp   
5           636685    Tesla Inc.     Elon Tusk    Edward Thorp   
6           636685    Tesla Inc.     Elon Tusk    Edward Thorp   
7          1216870     Microsoft   Will Grates    Edward Thorp   
8          2200450       Walmart   Will Grates    Edward Thorp   
9           405886         Apple  Cindy Phoner  Claude Shannon   
10          470248  Exxon Mobile  Cindy Phoner  Claude Shannon   
11          698032           ATT  Cindy Phoner  Claude Shannon   
12          698032           ATT  Cindy Phoner  Claude Shannon   
13          902797    CVS Health  Emma Gordian  Claude Shannon   
14         2046943    Salesforce  Emma Gordian  Claude Shannon   
15         2169499         Cisco  Emma Gordian  Claude Shannon   
16         2169499         Cisco  Emma Gordian  Claude Shannon   

            Product  Licenses  Sale Price        Status  
0         Analytics       150     2100000     Presented  
1        Prediction       150      700000     Presented  
2          Tracking       300      350000  Under Review  
3         Analytics       150     2450000          Lost  
4         Analytics       300     4550000           Won  
5         Analytics       300     2800000  Under Review  
6        Prediction       150      700000     Presented  
7          Tracking       300      350000  Under Review  
8         Analytics       150     2450000          Lost  
9         Analytics       300     4550000           Won  
10        Analytics       150     2100000     Presented  
11         Tracking       150      350000  Under Review  
12       Prediction       150      700000     Presented  
13         Tracking       450      490000           Won  
14        Analytics       750     7000000           Won  
15        Analytics       300     4550000          Lost  
16  GPS Positioning       300      350000     Presented

In [465]:
pd.pivot_table(data=df,index=['Account Manager','Contact'],values=['Sale Price'],aggfunc='sum')

Sale Price
Account Manager Contact                 
Claude Shannon  Cindy Phoner     7700000
                Emma Gordian    12390000
Edward Thorp    Elon Tusk        8050000
                Larry Pager      5600000
                Will Grates      2800000

In [468]:
pd.pivot_table(data=df,index=['Account Manager','Contact'],columns=['Product'],fill_value=0,values=['Sale Price'],aggfunc=[np.sum])

sum                                    
                             Sale Price                                    
Product                       Analytics GPS Positioning Prediction Tracking
Account Manager Contact                                                    
Claude Shannon  Cindy Phoner    6650000               0     700000   350000
                Emma Gordian   11550000          350000          0   490000
Edward Thorp    Elon Tusk       7350000               0     700000        0
                Larry Pager     4550000               0     700000   350000
                Will Grates     2450000               0          0   350000

In [469]:
pd.pivot_table(data=df,index=['Account Manager','Contact','Product'],fill_value=0,values=['Sale Price'],aggfunc=[np.sum])

sum
                                             Sale Price
Account Manager Contact      Product                   
Claude Shannon  Cindy Phoner Analytics          6650000
                             Prediction          700000
                             Tracking            350000
                Emma Gordian Analytics         11550000
                             GPS Positioning     350000
                             Tracking            490000
Edward Thorp    Elon Tusk    Analytics          7350000
                             Prediction          700000
                Larry Pager  Analytics          4550000
                             Prediction          700000
                             Tracking            350000
                Will Grates  Analytics          2450000
                             Tracking            350000

In [470]:
pd.pivot_table(data=df,margins=True,index=['Account Manager','Contact','Product'],fill_value=0,values=['Sale Price'],aggfunc=[np.sum])

sum
                                             Sale Price
Account Manager Contact      Product                   
Claude Shannon  Cindy Phoner Analytics          6650000
                             Prediction          700000
                             Tracking            350000
                Emma Gordian Analytics         11550000
                             GPS Positioning     350000
                             Tracking            490000
Edward Thorp    Elon Tusk    Analytics          7350000
                             Prediction          700000
                Larry Pager  Analytics          4550000
                             Prediction          700000
                             Tracking            350000
                Will Grates  Analytics          2450000
                             Tracking            350000
All                                            36540000